CREATE TABLE [MStar].[MEODPriceHistory] (
    [MEODPriceHistoryId] uniqueidentifier NOT NULL,
    [CreatedDate] datetime2 NOT NULL,
    [UpdatedDate] datetime2 NOT NULL,
    [ExchangeId] nvarchar(max) NULL,
    [CompanyName] nvarchar(max) NULL,
    [Symbol] nvarchar(max) NULL,
    [CUSIP] nvarchar(max) NULL,
    [CIK] nvarchar(max) NULL,
    [ISIN] nvarchar(max) NULL,
    [SEDOL] nvarchar(max) NULL,
    [ShareClassId] nvarchar(max) NULL,
    [TradingDate] datetime2 NOT NULL,
    [OpenPrice] decimal(18, 2) NULL,
    [HighPrice] decimal(18, 2) NULL,
    [LowPrice] decimal(18, 2) NULL,
    [ClosePrice] decimal(18, 2) NULL,
    [Volume] int NOT NULL,
    [PriceCurrencyId] nvarchar(max) NULL,
    CONSTRAINT [PK_MEODPriceHistory] PRIMARY KEY ([MEODPriceHistoryId])
);

GO

CREATE TABLE [MStar].[MFinancialHealthRatio] (
    [MFinancialHealthRatioId] uniqueidentifier NOT NULL,
    [CreatedDate] datetime2 NOT NULL,
    [UpdatedDate] datetime2 NOT NULL,
    [ExchangeId] nvarchar(max) NULL,
    [CompanyName] nvarchar(max) NULL,
    [Symbol] nvarchar(max) NULL,
    [CUSIP] nvarchar(max) NULL,
    [CIK] nvarchar(max) NULL,
    [ISIN] nvarchar(max) NULL,
    [SEDOL] nvarchar(max) NULL,
    [ShareClassId] nvarchar(max) NULL,
    [ReportDate] datetime2 NOT NULL,
    [PeriodEndingDate] datetime2 NOT NULL,
    [FileDate] datetime2 NULL,
    [StatementType] nvarchar(max) NULL,
    [DataType] nvarchar(max) NULL,
    [Interim] nvarchar(max) NULL,
    [FiscalYearEnd] int NOT NULL,
    [CurrentRatio] decimal(18, 2) NULL,
    [QuickRatio] decimal(18, 2) NULL,
    [DebtTotalCapitalRatio] decimal(18, 2) NULL,
    [DebtEquityRatio] decimal(18, 2) NULL,
    [FinancialLeverage] decimal(18, 2) NULL,
    [TotalDebtToEquity] decimal(18, 2) NULL,
    [AccessionNumber] nvarchar(max) NULL,
    [FormType] nvarchar(max) NULL,
    [DebttoAssets] decimal(18, 2) NULL,
    [CommonEquityToAssets] decimal(18, 2) NULL,
    CONSTRAINT [PK_MFinancialHealthRatio] PRIMARY KEY ([MFinancialHealthRatioId])
);

GO

CREATE TABLE [MStar].[MGrowthRatio] (
    [MGrowthRatioId] uniqueidentifier NOT NULL,
    [CreatedDate] datetime2 NOT NULL,
    [UpdatedDate] datetime2 NOT NULL,
    [ExchangeId] nvarchar(max) NULL,
    [CompanyName] nvarchar(max) NULL,
    [Symbol] nvarchar(max) NULL,
    [CUSIP] nvarchar(max) NULL,
    [CIK] nvarchar(max) NULL,
    [ISIN] nvarchar(max) NULL,
    [SEDOL] nvarchar(max) NULL,
    [ShareClassId] nvarchar(max) NULL,
    [ReportDate] datetime2 NOT NULL,
    [PeriodEndingDate] datetime2 NOT NULL,
    [FileDate] datetime2 NULL,
    [StatementType] nvarchar(max) NULL,
    [DataType] nvarchar(max) NULL,
    [Interim] nvarchar(max) NULL,
    [FiscalYearEnd] int NOT NULL,
    [DilutedEPS3MonthSamePeriodGrowth] decimal(18, 2) NULL,
    [DilutedEPS6MonthSamePeriodGrowth] decimal(18, 2) NULL,
    [DilutedEPS9MonthSamePeriodGrowth] decimal(18, 2) NULL,
    [DilutedEPSSequentialGrowth] decimal(18, 2) NULL,
    [DilutedEPS1YearGrowth] decimal(18, 2) NULL,
    [DilutedEPS3YearGrowth] decimal(18, 2) NULL,
    [DilutedEPS5YearGrowth] decimal(18, 2) NULL,
    [DilutedEPS10YearGrowth] decimal(18, 2) NULL,
    [DilutedContinuousEPS3MonthSamePeriodGrowth] decimal(18, 2) NULL,
    [DilutedContinuousEPS6MonthSamePeriodGrowth] decimal(18, 2) NULL,
    [DilutedContinuousEPS9MonthSamePeriodGrowth] decimal(18, 2) NULL,
    [DilutedContinuousEPSSequentialGrowth] decimal(18, 2) NULL,
    [DilutedContinuousEPS1YearGrowth] decimal(18, 2) NULL,
    [DilutedContinuousEPS3YearGrowth] decimal(18, 2) NULL,
    [DilutedContinuousEPS5YearGrowth] decimal(18, 2) NULL,
    [DilutedContinuousEPS10YearGrowth] decimal(18, 2) NULL,
    [Dividend3MonthSamePeriodGrowth] decimal(18, 2) NULL,
    [Dividend6MonthSamePeriodGrowth] decimal(18, 2) NULL,
    [Dividend9MonthSamePeriodGrowth] decimal(18, 2) NULL,
    [DividendSequentialGrowth] decimal(18, 2) NULL,
    [Dividend1YearGrowth] decimal(18, 2) NULL,
    [Dividend3YearGrowth] decimal(18, 2) NULL,
    [Dividend5YearGrowth] decimal(18, 2) NULL,
    [Dividend10YearGrowth] decimal(18, 2) NULL,
    [EquityPerShare3MonthSamePeriodGrowth] decimal(18, 2) NULL,
    [EquityPerShare6MonthSamePeriodGrowth] decimal(18, 2) NULL,
    [EquityPerShare9MonthSamePeriodGrowth] decimal(18, 2) NULL,
    [EquityPerShareSequentialGrowth] decimal(18, 2) NULL,
    [EquityPerShare1YearGrowth] decimal(18, 2) NULL,
    [EquityPerShare3YearGrowth] decimal(18, 2) NULL,
    [EquityPerShare5YearGrowth] decimal(18, 2) NULL,
    [EquityPerShare10YearGrowth] decimal(18, 2) NULL,
    [Revenue3MonthSamePeriodGrowth] decimal(18, 2) NULL,
    [Revenue6MonthSamePeriodGrowth] decimal(18, 2) NULL,
    [Revenue9MonthSamePeriodGrowth] decimal(18, 2) NULL,
    [RevenueSequentialGrowth] decimal(18, 2) NULL,
    [Revenue1YearGrowth] decimal(18, 2) NULL,
    [Revenue3YearGrowth] decimal(18, 2) NULL,
    [Revenue5YearGrowth] decimal(18, 2) NULL,
    [Revenue10YearGrowth] decimal(18, 2) NULL,
    [OperatingIncome3MonthSamePeriodGrowth] decimal(18, 2) NULL,
    [OperatingIncome6MonthSamePeriodGrowth] decimal(18, 2) NULL,
    [OperatingIncome9MonthSamePeriodGrowth] decimal(18, 2) NULL,
    [OperatingIncomeSequentialGrowth] decimal(18, 2) NULL,
    [OperatingIncome1YearGrowth] decimal(18, 2) NULL,
    [OperatingIncome3YearGrowth] decimal(18, 2) NULL,
    [OperatingIncome5YearGrowth] decimal(18, 2) NULL,
    [OperatingIncome10YearGrowth] decimal(18, 2) NULL,
    [NetIncome3MonthSamePeriodGrowth] decimal(18, 2) NULL,
    [NetIncome6MonthSamePeriodGrowth] decimal(18, 2) NULL,
    [NetIncome9MonthSamePeriodGrowth] decimal(18, 2) NULL,
    [NetIncomeSequentialGrowth] decimal(18, 2) NULL,
    [NetIncome1YearGrowth] decimal(18, 2) NULL,
    [NetIncome3YearGrowth] decimal(18, 2) NULL,
    [NetIncome5YearGrowth] decimal(18, 2) NULL,
    [NetIncome10YearGrowth] decimal(18, 2) NULL,
    [NetIncomeContOps3MonthSamePeriodGrowth] decimal(18, 2) NULL,
    [NetIncomeContOps6MonthSamePeriodGrowth] decimal(18, 2) NULL,
    [NetIncomeContOps9MonthSamePeriodGrowth] decimal(18, 2) NULL,
    [NetIncomeContOpsSequentialGrowth] decimal(18, 2) NULL,
    [NetIncomeContOps1YearGrowth] decimal(18, 2) NULL,
    [NetIncomeContOps3YearGrowth] decimal(18, 2) NULL,
    [NetIncomeContOps5YearGrowth] decimal(18, 2) NULL,
    [NetIncomeContOps10YearGrowth] decimal(18, 2) NULL,
    [CFO3MonthSamePeriodGrowth] decimal(18, 2) NULL,
    [CFO6MonthSamePeriodGrowth] decimal(18, 2) NULL,
    [CFO9MonthSamePeriodGrowth] decimal(18, 2) NULL,
    [CFOSequentialGrowth] decimal(18, 2) NULL,
    [CFO1YearGrowth] decimal(18, 2) NULL,
    [CFO3YearGrowth] decimal(18, 2) NULL,
    [CFO5YearGrowth] decimal(18, 2) NULL,
    [CFO10YearGrowth] decimal(18, 2) NULL,
    [FCF3MonthSamePeriodGrowth] decimal(18, 2) NULL,
    [FCF6MonthSamePeriodGrowth] decimal(18, 2) NULL,
    [FCF9MonthSamePeriodGrowth] decimal(18, 2) NULL,
    [FCFSequentialGrowth] decimal(18, 2) NULL,
    [FCF1YearGrowth] decimal(18, 2) NULL,
    [FCF3YearGrowth] decimal(18, 2) NULL,
    [FCF5YearGrowth] decimal(18, 2) NULL,
    [FCF10YearGrowth] decimal(18, 2) NULL,
    [OperatingRevenue3MonthSamePeriodGrowth] decimal(18, 2) NULL,
    [OperatingRevenue6MonthSamePeriodGrowth] decimal(18, 2) NULL,
    [OperatingRevenue9MonthSamePeriodGrowth] decimal(18, 2) NULL,
    [OperatingRevenueSequentialGrowth] decimal(18, 2) NULL,
    [OperatingRevenue1YearGrowth] decimal(18, 2) NULL,
    [OperatingRevenue3YearGrowth] decimal(18, 2) NULL,
    [OperatingRevenue5YearGrowth] decimal(18, 2) NULL,
    [OperatingRevenue10YearGrowth] decimal(18, 2) NULL,
    [GrowthAnnCapitalSpending5Year] decimal(18, 2) NULL,
    [GrowthAnnGrossProfit5Year] decimal(18, 2) NULL,
    [AvgGrossMargin5Year] decimal(18, 2) NULL,
    [AvgPostTaxMargin5Year] decimal(18, 2) NULL,
    [AvgPreTaxMargin5Year] decimal(18, 2) NULL,
    [AvgNetProfitMargin5Year] decimal(18, 2) NULL,
    [AvgRetCommonEquity5Year] decimal(18, 2) NULL,
    [AvgRetAssets5Year] decimal(18, 2) NULL,
    [AvgRetInvestedCapital5Year] decimal(18, 2) NULL,
    [AccessionNumber] nvarchar(max) NULL,
    [FormType] nvarchar(max) NULL,
    [RegressionGrowthOperatingRevenue5Years] decimal(18, 2) NULL,
    [NormalizedDilutedEPSGrowth1year] decimal(18, 2) NULL,
    [NormalizedDilutedEPSGrowth3year] decimal(18, 2) NULL,
    [NormalizedDilutedEPSGrowth5year] decimal(18, 2) NULL,
    [NormalizedDilutedEPSGrowth10year] decimal(18, 2) NULL,
    [NormalizedDilutedEPSSamePeriodGrowth3months] decimal(18, 2) NULL,
    [NormalizedDilutedEPSSamePeriodGrowth6months] decimal(18, 2) NULL,
    [NormalizedDilutedEPSSamePeriodGrowth9months] decimal(18, 2) NULL,
    [NormalizedDilutedEPSSequentialGrowth] decimal(18, 2) NULL,
    [NormalizedBasicEPSGrowth1year] decimal(18, 2) NULL,
    [NormalizedBasicEPSGrowth3year] decimal(18, 2) NULL,
    [NormalizedBasicEPSGrowth5year] decimal(18, 2) NULL,
    [NormalizedBasicEPSGrowth10year] decimal(18, 2) NULL,
    [NormalizedBasicEPSSamePeriodGrowth3months] decimal(18, 2) NULL,
    [NormalizedBasicEPSSamePeriodGrowth6months] decimal(18, 2) NULL,
    [NormalizedBasicEPSSamePeriodGrowth9months] decimal(18, 2) NULL,
    [NormalizedBasicEPSSequentialGrowth] decimal(18, 2) NULL,
    CONSTRAINT [PK_MGrowthRatio] PRIMARY KEY ([MGrowthRatioId])
);

GO

CREATE TABLE [MStar].[MMonthlyMarketCapitalizationHistory] (
    [MMonthlyMarketCapitalizationHistoryId] uniqueidentifier NOT NULL,
    [CreatedDate] datetime2 NOT NULL,
    [UpdatedDate] datetime2 NOT NULL,
    [ExchangeId] nvarchar(max) NULL,
    [CompanyName] nvarchar(max) NULL,
    [Symbol] nvarchar(max) NULL,
    [CUSIP] nvarchar(max) NULL,
    [CIK] nvarchar(max) NULL,
    [ISIN] nvarchar(max) NULL,
    [SEDOL] nvarchar(max) NULL,
    [ShareClassId] nvarchar(max) NULL,
    [MarketCapDate] datetime2 NOT NULL,
    [MarketCap] bigint NOT NULL,
    [EnterpriseValue] bigint NOT NULL,
    [CurrencyId] nvarchar(max) NULL,
    [SharesOutstanding] bigint NOT NULL,
    [SharesDate] datetime2 NOT NULL,
    CONSTRAINT [PK_MMonthlyMarketCapitalizationHistory] PRIMARY KEY ([MMonthlyMarketCapitalizationHistoryId])
);

GO

CREATE TABLE [MStar].[MQuantitativeRating] (
    [MQuantitativeRatingId] uniqueidentifier NOT NULL,
    [CreatedDate] datetime2 NOT NULL,
    [UpdatedDate] datetime2 NOT NULL,
    [ExchangeId] nvarchar(max) NULL,
    [CompanyName] nvarchar(max) NULL,
    [Symbol] nvarchar(max) NULL,
    [CUSIP] nvarchar(max) NULL,
    [CIK] nvarchar(max) NULL,
    [ISIN] nvarchar(max) NULL,
    [SEDOL] nvarchar(max) NULL,
    [ShareClassId] nvarchar(max) NULL,
    [AsOfDate] datetime2 NOT NULL,
    [QuantitativeMoat] decimal(18, 2) NULL,
    [QuantitativeMoatLabel] nvarchar(max) NULL,
    [QuantitativeValuation] decimal(18, 2) NULL,
    [QuantitativeValuationUpdateTime] datetime2 NOT NULL,
    [QuantitativeValuationLabel] nvarchar(max) NULL,
    [QuantitativeValuationLabelUpdateTime] datetime2 NOT NULL,
    [QuantitativeValuationUncertainty] decimal(18, 2) NULL,
    [QuantitativeValuationUncertaintyLabel] nvarchar(max) NULL,
    [QuantitativeFinancialHealth] decimal(18, 2) NULL,
    [QuantitativeFinancialHealthLabel] nvarchar(max) NULL,
    [SolvencyScore] decimal(18, 2) NULL,
    [QuantitativeFinancialHealthDecile] int NOT NULL,
    [QuantitativeStarRating] int NOT NULL,
    [QuantitativeStarRatingUpdateTime] datetime2 NOT NULL,
    [QuantitativeFairValue] decimal(18, 2) NULL,
    [QuantitativeFairValueUpdateTime] datetime2 NOT NULL,
    CONSTRAINT [PK_MQuantitativeRating] PRIMARY KEY ([MQuantitativeRatingId])
);

GO

CREATE TABLE [MStar].[MValuationRatio] (
    [MValuationRatioId] uniqueidentifier NOT NULL,
    [CreatedDate] datetime2 NOT NULL,
    [UpdatedDate] datetime2 NOT NULL,
    [ExchangeId] nvarchar(max) NULL,
    [CompanyName] nvarchar(max) NULL,
    [Symbol] nvarchar(max) NULL,
    [CUSIP] nvarchar(max) NULL,
    [CIK] nvarchar(max) NULL,
    [ISIN] nvarchar(max) NULL,
    [SEDOL] nvarchar(max) NULL,
    [ShareClassId] nvarchar(max) NULL,
    [AsOfDate] datetime2 NOT NULL,
    [SalesPerShare] decimal(18, 2) NULL,
    [GrowthAnnSalesPerShare5Year] decimal(18, 2) NULL,
    [BookValuePerShare] decimal(18, 2) NULL,
    [CFPerShare] decimal(18, 2) NULL,
    [FCFPerShare] decimal(18, 2) NULL,
    [PriceToEPS] decimal(18, 2) NULL,
    [RatioPE5YearHigh] decimal(18, 2) NULL,
    [RatioPE5YearLow] decimal(18, 2) NULL,
    [PriceToBook] decimal(18, 2) NULL,
    [PriceToSales] decimal(18, 2) NULL,
    [PriceToCashFlow] decimal(18, 2) NULL,
    [PriceToFreeCashFlow] decimal(18, 2) NULL,
    [DivRate] decimal(18, 2) NULL,
    [DividendYield] decimal(18, 2) NULL,
    [DivPayoutTotOps] decimal(18, 2) NULL,
    [DivPayout5Year] decimal(18, 2) NULL,
    [DivYield5Year] decimal(18, 2) NULL,
    [PayoutRatio] decimal(18, 2) NULL,
    [SustainableGrowthRate] decimal(18, 2) NULL,
    [CashReturn] decimal(18, 2) NULL,
    [ForwardEarningYield] decimal(18, 2) NULL,
    [PEGRatio] decimal(18, 2) NULL,
    [PEGPayback] decimal(18, 2) NULL,
    [ForwardDividendYield] decimal(18, 2) NULL,
    [ForwardPERatio] decimal(18, 2) NULL,
    [TangibleBookValuePerShare] decimal(18, 2) NULL,
    [TangibleBVPerShare3YrAvg] decimal(18, 2) NULL,
    [TangibleBVPerShare5YrAvg] decimal(18, 2) NULL,
    [EVToEBITDA] decimal(18, 2) NULL,
    [RatioPE5YearAverage] decimal(18, 2) NULL,
    [NormalizedPERatio] decimal(18, 2) NULL,
    [FCFYield] decimal(18, 2) NULL,
    [EVToForwardEBIT] decimal(18, 2) NULL,
    [EVToForwardEBITDA] decimal(18, 2) NULL,
    [EVToForwardRevenue] decimal(18, 2) NULL,
    [TwoYearsEVToForwardEBIT] decimal(18, 2) NULL,
    [TwoYearsEVToForwardEBITDA] decimal(18, 2) NULL,
    [FirstYearEstimatedEPSGrowth] decimal(18, 2) NULL,
    [SecondYearEstimatedEPSGrowth] decimal(18, 2) NULL,
    [NormalizedPEG] decimal(18, 2) NULL,
    [EarningYield] decimal(18, 2) NULL,
    [SalesYield] decimal(18, 2) NULL,
    [BookValueYield] decimal(18, 2) NULL,
    [CashFlowYield] decimal(18, 2) NULL,
    [ForwardDividend] decimal(18, 2) NULL,
    [WorkingCapitalPerShare] decimal(18, 2) NULL,
    [WorkingCapitalPerShare3YrAvg] decimal(18, 2) NULL,
    [WorkingCapitalPerShare5YrAvg] decimal(18, 2) NULL,
    [BuyBackYield] decimal(18, 2) NULL,
    [TotalYield] decimal(18, 2) NULL,
    [PricetoEBITDA] decimal(18, 2) NULL,
    [ForwardROE] decimal(18, 2) NULL,
    [ForwardROA] decimal(18, 2) NULL,
    [TwoYearsForwardEarningYield] decimal(18, 2) NULL,
    [TwoYearsForwardPERatio] decimal(18, 2) NULL,
    [TotalAssetPerShare] decimal(18, 2) NULL,
    [EVtoRevenue] decimal(18, 2) NULL,
    [EVtoPreTaxIncome] decimal(18, 2) NULL,
    [EVtoTotalAssets] decimal(18, 2) NULL,
    [EVtoFCF] decimal(18, 2) NULL,
    [EVtoEBIT] decimal(18, 2) NULL,
    [FFOPerShare] decimal(18, 2) NULL,
    [PricetoCashRatio] decimal(18, 2) NULL,
    [CAPERatio] decimal(18, 2) NULL,
    CONSTRAINT [PK_MValuationRatio] PRIMARY KEY ([MValuationRatioId])
);

GO

CREATE TABLE [MStar].[TEODPriceHistory] (
    [Id] uniqueidentifier NOT NULL,
    [IngestionTaskId] uniqueidentifier NOT NULL,
    [TradingDate] datetime2 NOT NULL,
    [OpenPrice] decimal(18, 2) NULL,
    [HighPrice] decimal(18, 2) NULL,
    [LowPrice] decimal(18, 2) NULL,
    [ClosePrice] decimal(18, 2) NULL,
    [Volume] int NOT NULL,
    [PriceCurrencyId] nvarchar(max) NULL,
    CONSTRAINT [PK_TEODPriceHistory] PRIMARY KEY ([Id])
);

GO

CREATE TABLE [MStar].[TFinancialHealthRatio] (
    [Id] uniqueidentifier NOT NULL,
    [IngestionTaskId] uniqueidentifier NOT NULL,
    [ReportDate] datetime2 NOT NULL,
    [PeriodEndingDate] datetime2 NOT NULL,
    [FileDate] datetime2 NULL,
    [StatementType] nvarchar(max) NULL,
    [DataType] nvarchar(max) NULL,
    [Interim] nvarchar(max) NULL,
    [FiscalYearEnd] int NOT NULL,
    [CurrentRatio] decimal(18, 2) NULL,
    [QuickRatio] decimal(18, 2) NULL,
    [DebtTotalCapitalRatio] decimal(18, 2) NULL,
    [DebtEquityRatio] decimal(18, 2) NULL,
    [FinancialLeverage] decimal(18, 2) NULL,
    [TotalDebtToEquity] decimal(18, 2) NULL,
    [AccessionNumber] nvarchar(max) NULL,
    [FormType] nvarchar(max) NULL,
    [DebttoAssets] decimal(18, 2) NULL,
    [CommonEquityToAssets] decimal(18, 2) NULL,
    CONSTRAINT [PK_TFinancialHealthRatio] PRIMARY KEY ([Id])
);

GO

CREATE TABLE [MStar].[TGrowthRatio] (
    [Id] uniqueidentifier NOT NULL,
    [IngestionTaskId] uniqueidentifier NOT NULL,
    [ReportDate] datetime2 NOT NULL,
    [PeriodEndingDate] datetime2 NOT NULL,
    [FileDate] datetime2 NULL,
    [StatementType] nvarchar(max) NULL,
    [DataType] nvarchar(max) NULL,
    [Interim] nvarchar(max) NULL,
    [FiscalYearEnd] int NOT NULL,
    [DilutedEPS3MonthSamePeriodGrowth] decimal(18, 2) NULL,
    [DilutedEPS6MonthSamePeriodGrowth] decimal(18, 2) NULL,
    [DilutedEPS9MonthSamePeriodGrowth] decimal(18, 2) NULL,
    [DilutedEPSSequentialGrowth] decimal(18, 2) NULL,
    [DilutedEPS1YearGrowth] decimal(18, 2) NULL,
    [DilutedEPS3YearGrowth] decimal(18, 2) NULL,
    [DilutedEPS5YearGrowth] decimal(18, 2) NULL,
    [DilutedEPS10YearGrowth] decimal(18, 2) NULL,
    [DilutedContinuousEPS3MonthSamePeriodGrowth] decimal(18, 2) NULL,
    [DilutedContinuousEPS6MonthSamePeriodGrowth] decimal(18, 2) NULL,
    [DilutedContinuousEPS9MonthSamePeriodGrowth] decimal(18, 2) NULL,
    [DilutedContinuousEPSSequentialGrowth] decimal(18, 2) NULL,
    [DilutedContinuousEPS1YearGrowth] decimal(18, 2) NULL,
    [DilutedContinuousEPS3YearGrowth] decimal(18, 2) NULL,
    [DilutedContinuousEPS5YearGrowth] decimal(18, 2) NULL,
    [DilutedContinuousEPS10YearGrowth] decimal(18, 2) NULL,
    [Dividend3MonthSamePeriodGrowth] decimal(18, 2) NULL,
    [Dividend6MonthSamePeriodGrowth] decimal(18, 2) NULL,
    [Dividend9MonthSamePeriodGrowth] decimal(18, 2) NULL,
    [DividendSequentialGrowth] decimal(18, 2) NULL,
    [Dividend1YearGrowth] decimal(18, 2) NULL,
    [Dividend3YearGrowth] decimal(18, 2) NULL,
    [Dividend5YearGrowth] decimal(18, 2) NULL,
    [Dividend10YearGrowth] decimal(18, 2) NULL,
    [EquityPerShare3MonthSamePeriodGrowth] decimal(18, 2) NULL,
    [EquityPerShare6MonthSamePeriodGrowth] decimal(18, 2) NULL,
    [EquityPerShare9MonthSamePeriodGrowth] decimal(18, 2) NULL,
    [EquityPerShareSequentialGrowth] decimal(18, 2) NULL,
    [EquityPerShare1YearGrowth] decimal(18, 2) NULL,
    [EquityPerShare3YearGrowth] decimal(18, 2) NULL,
    [EquityPerShare5YearGrowth] decimal(18, 2) NULL,
    [EquityPerShare10YearGrowth] decimal(18, 2) NULL,
    [Revenue3MonthSamePeriodGrowth] decimal(18, 2) NULL,
    [Revenue6MonthSamePeriodGrowth] decimal(18, 2) NULL,
    [Revenue9MonthSamePeriodGrowth] decimal(18, 2) NULL,
    [RevenueSequentialGrowth] decimal(18, 2) NULL,
    [Revenue1YearGrowth] decimal(18, 2) NULL,
    [Revenue3YearGrowth] decimal(18, 2) NULL,
    [Revenue5YearGrowth] decimal(18, 2) NULL,
    [Revenue10YearGrowth] decimal(18, 2) NULL,
    [OperatingIncome3MonthSamePeriodGrowth] decimal(18, 2) NULL,
    [OperatingIncome6MonthSamePeriodGrowth] decimal(18, 2) NULL,
    [OperatingIncome9MonthSamePeriodGrowth] decimal(18, 2) NULL,
    [OperatingIncomeSequentialGrowth] decimal(18, 2) NULL,
    [OperatingIncome1YearGrowth] decimal(18, 2) NULL,
    [OperatingIncome3YearGrowth] decimal(18, 2) NULL,
    [OperatingIncome5YearGrowth] decimal(18, 2) NULL,
    [OperatingIncome10YearGrowth] decimal(18, 2) NULL,
    [NetIncome3MonthSamePeriodGrowth] decimal(18, 2) NULL,
    [NetIncome6MonthSamePeriodGrowth] decimal(18, 2) NULL,
    [NetIncome9MonthSamePeriodGrowth] decimal(18, 2) NULL,
    [NetIncomeSequentialGrowth] decimal(18, 2) NULL,
    [NetIncome1YearGrowth] decimal(18, 2) NULL,
    [NetIncome3YearGrowth] decimal(18, 2) NULL,
    [NetIncome5YearGrowth] decimal(18, 2) NULL,
    [NetIncome10YearGrowth] decimal(18, 2) NULL,
    [NetIncomeContOps3MonthSamePeriodGrowth] decimal(18, 2) NULL,
    [NetIncomeContOps6MonthSamePeriodGrowth] decimal(18, 2) NULL,
    [NetIncomeContOps9MonthSamePeriodGrowth] decimal(18, 2) NULL,
    [NetIncomeContOpsSequentialGrowth] decimal(18, 2) NULL,
    [NetIncomeContOps1YearGrowth] decimal(18, 2) NULL,
    [NetIncomeContOps3YearGrowth] decimal(18, 2) NULL,
    [NetIncomeContOps5YearGrowth] decimal(18, 2) NULL,
    [NetIncomeContOps10YearGrowth] decimal(18, 2) NULL,
    [CFO3MonthSamePeriodGrowth] decimal(18, 2) NULL,
    [CFO6MonthSamePeriodGrowth] decimal(18, 2) NULL,
    [CFO9MonthSamePeriodGrowth] decimal(18, 2) NULL,
    [CFOSequentialGrowth] decimal(18, 2) NULL,
    [CFO1YearGrowth] decimal(18, 2) NULL,
    [CFO3YearGrowth] decimal(18, 2) NULL,
    [CFO5YearGrowth] decimal(18, 2) NULL,
    [CFO10YearGrowth] decimal(18, 2) NULL,
    [FCF3MonthSamePeriodGrowth] decimal(18, 2) NULL,
    [FCF6MonthSamePeriodGrowth] decimal(18, 2) NULL,
    [FCF9MonthSamePeriodGrowth] decimal(18, 2) NULL,
    [FCFSequentialGrowth] decimal(18, 2) NULL,
    [FCF1YearGrowth] decimal(18, 2) NULL,
    [FCF3YearGrowth] decimal(18, 2) NULL,
    [FCF5YearGrowth] decimal(18, 2) NULL,
    [FCF10YearGrowth] decimal(18, 2) NULL,
    [OperatingRevenue3MonthSamePeriodGrowth] decimal(18, 2) NULL,
    [OperatingRevenue6MonthSamePeriodGrowth] decimal(18, 2) NULL,
    [OperatingRevenue9MonthSamePeriodGrowth] decimal(18, 2) NULL,
    [OperatingRevenueSequentialGrowth] decimal(18, 2) NULL,
    [OperatingRevenue1YearGrowth] decimal(18, 2) NULL,
    [OperatingRevenue3YearGrowth] decimal(18, 2) NULL,
    [OperatingRevenue5YearGrowth] decimal(18, 2) NULL,
    [OperatingRevenue10YearGrowth] decimal(18, 2) NULL,
    [GrowthAnnCapitalSpending5Year] decimal(18, 2) NULL,
    [GrowthAnnGrossProfit5Year] decimal(18, 2) NULL,
    [AvgGrossMargin5Year] decimal(18, 2) NULL,
    [AvgPostTaxMargin5Year] decimal(18, 2) NULL,
    [AvgPreTaxMargin5Year] decimal(18, 2) NULL,
    [AvgNetProfitMargin5Year] decimal(18, 2) NULL,
    [AvgRetCommonEquity5Year] decimal(18, 2) NULL,
    [AvgRetAssets5Year] decimal(18, 2) NULL,
    [AvgRetInvestedCapital5Year] decimal(18, 2) NULL,
    [AccessionNumber] nvarchar(max) NULL,
    [FormType] nvarchar(max) NULL,
    [RegressionGrowthOperatingRevenue5Years] decimal(18, 2) NULL,
    [NormalizedDilutedEPSGrowth1year] decimal(18, 2) NULL,
    [NormalizedDilutedEPSGrowth3year] decimal(18, 2) NULL,
    [NormalizedDilutedEPSGrowth5year] decimal(18, 2) NULL,
    [NormalizedDilutedEPSGrowth10year] decimal(18, 2) NULL,
    [NormalizedDilutedEPSSamePeriodGrowth3months] decimal(18, 2) NULL,
    [NormalizedDilutedEPSSamePeriodGrowth6months] decimal(18, 2) NULL,
    [NormalizedDilutedEPSSamePeriodGrowth9months] decimal(18, 2) NULL,
    [NormalizedDilutedEPSSequentialGrowth] decimal(18, 2) NULL,
    [NormalizedBasicEPSGrowth1year] decimal(18, 2) NULL,
    [NormalizedBasicEPSGrowth3year] decimal(18, 2) NULL,
    [NormalizedBasicEPSGrowth5year] decimal(18, 2) NULL,
    [NormalizedBasicEPSGrowth10year] decimal(18, 2) NULL,
    [NormalizedBasicEPSSamePeriodGrowth3months] decimal(18, 2) NULL,
    [NormalizedBasicEPSSamePeriodGrowth6months] decimal(18, 2) NULL,
    [NormalizedBasicEPSSamePeriodGrowth9months] decimal(18, 2) NULL,
    [NormalizedBasicEPSSequentialGrowth] decimal(18, 2) NULL,
    CONSTRAINT [PK_TGrowthRatio] PRIMARY KEY ([Id])
);

GO

CREATE TABLE [MStar].[TMonthlyMarketCapitalizationHistory] (
    [Id] uniqueidentifier NOT NULL,
    [IngestionTaskId] uniqueidentifier NOT NULL,
    [MarketCapDate] datetime2 NOT NULL,
    [MarketCap] bigint NOT NULL,
    [EnterpriseValue] bigint NOT NULL,
    [CurrencyId] nvarchar(max) NULL,
    [SharesOutstanding] bigint NOT NULL,
    [SharesDate] datetime2 NOT NULL,
    CONSTRAINT [PK_TMonthlyMarketCapitalizationHistory] PRIMARY KEY ([Id])
);

GO

CREATE TABLE [MStar].[TQuantitativeRating] (
    [Id] uniqueidentifier NOT NULL,
    [IngestionTaskId] uniqueidentifier NOT NULL,
    [AsOfDate] datetime2 NOT NULL,
    [QuantitativeMoat] decimal(18, 2) NULL,
    [QuantitativeMoatLabel] nvarchar(max) NULL,
    [QuantitativeValuation] decimal(18, 2) NULL,
    [QuantitativeValuationUpdateTime] datetime2 NOT NULL,
    [QuantitativeValuationLabel] nvarchar(max) NULL,
    [QuantitativeValuationLabelUpdateTime] datetime2 NOT NULL,
    [QuantitativeValuationUncertainty] decimal(18, 2) NULL,
    [QuantitativeValuationUncertaintyLabel] nvarchar(max) NULL,
    [QuantitativeFinancialHealth] decimal(18, 2) NULL,
    [QuantitativeFinancialHealthLabel] nvarchar(max) NULL,
    [SolvencyScore] decimal(18, 2) NULL,
    [QuantitativeFinancialHealthDecile] int NOT NULL,
    [QuantitativeStarRating] int NOT NULL,
    [QuantitativeStarRatingUpdateTime] datetime2 NOT NULL,
    [QuantitativeFairValue] decimal(18, 2) NULL,
    [QuantitativeFairValueUpdateTime] datetime2 NOT NULL,
    CONSTRAINT [PK_TQuantitativeRating] PRIMARY KEY ([Id])
);

GO

CREATE TABLE [MStar].[TValuationRatio] (
    [Id] uniqueidentifier NOT NULL,
    [IngestionTaskId] uniqueidentifier NOT NULL,
    [AsOfDate] datetime2 NOT NULL,
    [SalesPerShare] decimal(18, 2) NULL,
    [GrowthAnnSalesPerShare5Year] decimal(18, 2) NULL,
    [BookValuePerShare] decimal(18, 2) NULL,
    [CFPerShare] decimal(18, 2) NULL,
    [FCFPerShare] decimal(18, 2) NULL,
    [PriceToEPS] decimal(18, 2) NULL,
    [RatioPE5YearHigh] decimal(18, 2) NULL,
    [RatioPE5YearLow] decimal(18, 2) NULL,
    [PriceToBook] decimal(18, 2) NULL,
    [PriceToSales] decimal(18, 2) NULL,
    [PriceToCashFlow] decimal(18, 2) NULL,
    [PriceToFreeCashFlow] decimal(18, 2) NULL,
    [DivRate] decimal(18, 2) NULL,
    [DividendYield] decimal(18, 2) NULL,
    [DivPayoutTotOps] decimal(18, 2) NULL,
    [DivPayout5Year] decimal(18, 2) NULL,
    [DivYield5Year] decimal(18, 2) NULL,
    [PayoutRatio] decimal(18, 2) NULL,
    [SustainableGrowthRate] decimal(18, 2) NULL,
    [CashReturn] decimal(18, 2) NULL,
    [ForwardEarningYield] decimal(18, 2) NULL,
    [PEGRatio] decimal(18, 2) NULL,
    [PEGPayback] decimal(18, 2) NULL,
    [ForwardDividendYield] decimal(18, 2) NULL,
    [ForwardPERatio] decimal(18, 2) NULL,
    [TangibleBookValuePerShare] decimal(18, 2) NULL,
    [TangibleBVPerShare3YrAvg] decimal(18, 2) NULL,
    [TangibleBVPerShare5YrAvg] decimal(18, 2) NULL,
    [EVToEBITDA] decimal(18, 2) NULL,
    [RatioPE5YearAverage] decimal(18, 2) NULL,
    [NormalizedPERatio] decimal(18, 2) NULL,
    [FCFYield] decimal(18, 2) NULL,
    [EVToForwardEBIT] decimal(18, 2) NULL,
    [EVToForwardEBITDA] decimal(18, 2) NULL,
    [EVToForwardRevenue] decimal(18, 2) NULL,
    [TwoYearsEVToForwardEBIT] decimal(18, 2) NULL,
    [TwoYearsEVToForwardEBITDA] decimal(18, 2) NULL,
    [FirstYearEstimatedEPSGrowth] decimal(18, 2) NULL,
    [SecondYearEstimatedEPSGrowth] decimal(18, 2) NULL,
    [NormalizedPEG] decimal(18, 2) NULL,
    [EarningYield] decimal(18, 2) NULL,
    [SalesYield] decimal(18, 2) NULL,
    [BookValueYield] decimal(18, 2) NULL,
    [CashFlowYield] decimal(18, 2) NULL,
    [ForwardDividend] decimal(18, 2) NULL,
    [WorkingCapitalPerShare] decimal(18, 2) NULL,
    [WorkingCapitalPerShare3YrAvg] decimal(18, 2) NULL,
    [WorkingCapitalPerShare5YrAvg] decimal(18, 2) NULL,
    [BuyBackYield] decimal(18, 2) NULL,
    [TotalYield] decimal(18, 2) NULL,
    [PricetoEBITDA] decimal(18, 2) NULL,
    [ForwardROE] decimal(18, 2) NULL,
    [ForwardROA] decimal(18, 2) NULL,
    [TwoYearsForwardEarningYield] decimal(18, 2) NULL,
    [TwoYearsForwardPERatio] decimal(18, 2) NULL,
    [TotalAssetPerShare] decimal(18, 2) NULL,
    [EVtoRevenue] decimal(18, 2) NULL,
    [EVtoPreTaxIncome] decimal(18, 2) NULL,
    [EVtoTotalAssets] decimal(18, 2) NULL,
    [EVtoFCF] decimal(18, 2) NULL,
    [EVtoEBIT] decimal(18, 2) NULL,
    [FFOPerShare] decimal(18, 2) NULL,
    [PricetoCashRatio] decimal(18, 2) NULL,
    [CAPERatio] decimal(18, 2) NULL,
    CONSTRAINT [PK_TValuationRatio] PRIMARY KEY ([Id])
);

GO

INSERT INTO [__EFMigrationsHistory] ([MigrationId], [ProductVersion])
VALUES (N'20200116084458_add-table-quantratios', N'3.1.0');

GO

