/****** Object:  StoredProcedure [dbo].[MergeValuationRatio]    Script Date: 1/17/2020 9:45:44 AM ******/
IF EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'MergeValuationRatio')
DROP PROCEDURE [dbo].[MergeValuationRatio]
GO

/****** Object:  StoredProcedure [dbo].[MergeValuationRatio]    Script Date: 1/17/2020 9:45:44 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

-- =============================================
-- Author:		Kevin Wu
-- Create date: 17th Jan 2020
-- Description:	Merge data from temporary job table [MStar].[TValuationRatio]
--				to master table [MStar].[MValuationRatio]
-- Example: EXECUTE MergeValuationRatio
--          To prevent timeout due to exceessive records of changes to merge,
--          added a limit of merging only the last 50 ingestion task,
--          Will require a recurring job to run this merge function to check of unprocessed tasks
-- =============================================
CREATE PROCEDURE [dbo].[MergeValuationRatio]
AS
BEGIN
	SET NOCOUNT ON;

    DECLARE @SummaryOfChanges TABLE(Change VARCHAR(20));
	DECLARE @UnprocessedTasks TABLE (id uniqueidentifier, CreatedDate DateTime);

	INSERT INTO @UnprocessedTasks
	SELECT DISTINCT TOP 50 IT.[IngestionTaskId], IT.[CreatedDate]
	FROM [MStar].[TValuationRatio] VR
	JOIN [dbo].[IngestionTasks] IT ON IT.[IngestionTaskId] = VR.[IngestionTaskId]
	WHERE IT.[IsProcessed] = 0;


	MERGE INTO [MStar].[MValuationRatio] AS TargetTable
	USING
	(SELECT GI.[ExchangeId]
      ,GI.[CompanyName]
      ,GI.[Symbol]
      ,GI.[CUSIP]
      ,GI.[CIK]
      ,GI.[ISIN]
      ,GI.[SEDOL]
      ,GI.[ShareClassId]
	  ,VR.[AsOfDate]
      ,VR.[SalesPerShare]
      ,VR.[GrowthAnnSalesPerShare5Year]
      ,VR.[BookValuePerShare]
      ,VR.[CFPerShare]
      ,VR.[FCFPerShare]
      ,VR.[PriceToEPS]
      ,VR.[RatioPE5YearHigh]
      ,VR.[RatioPE5YearLow]
      ,VR.[PriceToBook]
      ,VR.[PriceToSales]
      ,VR.[PriceToCashFlow]
      ,VR.[PriceToFreeCashFlow]
      ,VR.[DivRate]
      ,VR.[DividendYield]
      ,VR.[DivPayoutTotOps]
      ,VR.[DivPayout5Year]
      ,VR.[DivYield5Year]
      ,VR.[PayoutRatio]
      ,VR.[SustainableGrowthRate]
      ,VR.[CashReturn]
      ,VR.[ForwardEarningYield]
      ,VR.[PEGRatio]
      ,VR.[PEGPayback]
      ,VR.[ForwardDividendYield]
      ,VR.[ForwardPERatio]
      ,VR.[TangibleBookValuePerShare]
      ,VR.[TangibleBVPerShare3YrAvg]
      ,VR.[TangibleBVPerShare5YrAvg]
      ,VR.[EVToEBITDA]
      ,VR.[RatioPE5YearAverage]
      ,VR.[NormalizedPERatio]
      ,VR.[FCFYield]
      ,VR.[EVToForwardEBIT]
      ,VR.[EVToForwardEBITDA]
      ,VR.[EVToForwardRevenue]
      ,VR.[TwoYearsEVToForwardEBIT]
      ,VR.[TwoYearsEVToForwardEBITDA]
      ,VR.[FirstYearEstimatedEPSGrowth]
      ,VR.[SecondYearEstimatedEPSGrowth]
      ,VR.[NormalizedPEG]
      ,VR.[EarningYield]
      ,VR.[SalesYield]
      ,VR.[BookValueYield]
      ,VR.[CashFlowYield]
      ,VR.[ForwardDividend]
      ,VR.[WorkingCapitalPerShare]
      ,VR.[WorkingCapitalPerShare3YrAvg]
      ,VR.[WorkingCapitalPerShare5YrAvg]
      ,VR.[BuyBackYield]
      ,VR.[TotalYield]
      ,VR.[PricetoEBITDA]
      ,VR.[ForwardROE]
      ,VR.[ForwardROA]
      ,VR.[TwoYearsForwardEarningYield]
      ,VR.[TwoYearsForwardPERatio]
      ,VR.[TotalAssetPerShare]
      ,VR.[EVtoRevenue]
      ,VR.[EVtoPreTaxIncome]
      ,VR.[EVtoTotalAssets]
      ,VR.[EVtoFCF]
      ,VR.[EVtoEBIT]
      ,VR.[FFOPerShare]
      ,VR.[PricetoCashRatio]
      ,VR.[CAPERatio]
	  FROM [MStar].[TValuationRatio] VR
	  JOIN (SELECT DISTINCT [IngestionTaskId]
							  ,[ExchangeId]
							  ,[CompanyName]
							  ,[Symbol]
							  ,[CUSIP]
							  ,[CIK]
							  ,[ISIN]
							  ,[SEDOL]
							  ,[ShareClassId] FROM [MStar].[TGeneralInfo]) GI 
		ON GI.[IngestionTaskId] = VR.[IngestionTaskId]
	  WHERE VR.[IngestionTaskId] IN (SELECT ID FROM @UnprocessedTasks))
	  AS SourceTable (
      [ExchangeId]
      ,[CompanyName]
      ,[Symbol]
      ,[CUSIP]
      ,[CIK]
      ,[ISIN]
      ,[SEDOL]
      ,[ShareClassId]
	  ,[AsOfDate]
      ,[SalesPerShare]
      ,[GrowthAnnSalesPerShare5Year]
      ,[BookValuePerShare]
      ,[CFPerShare]
      ,[FCFPerShare]
      ,[PriceToEPS]
      ,[RatioPE5YearHigh]
      ,[RatioPE5YearLow]
      ,[PriceToBook]
      ,[PriceToSales]
      ,[PriceToCashFlow]
      ,[PriceToFreeCashFlow]
      ,[DivRate]
      ,[DividendYield]
      ,[DivPayoutTotOps]
      ,[DivPayout5Year]
      ,[DivYield5Year]
      ,[PayoutRatio]
      ,[SustainableGrowthRate]
      ,[CashReturn]
      ,[ForwardEarningYield]
      ,[PEGRatio]
      ,[PEGPayback]
      ,[ForwardDividendYield]
      ,[ForwardPERatio]
      ,[TangibleBookValuePerShare]
      ,[TangibleBVPerShare3YrAvg]
      ,[TangibleBVPerShare5YrAvg]
      ,[EVToEBITDA]
      ,[RatioPE5YearAverage]
      ,[NormalizedPERatio]
      ,[FCFYield]
      ,[EVToForwardEBIT]
      ,[EVToForwardEBITDA]
      ,[EVToForwardRevenue]
      ,[TwoYearsEVToForwardEBIT]
      ,[TwoYearsEVToForwardEBITDA]
      ,[FirstYearEstimatedEPSGrowth]
      ,[SecondYearEstimatedEPSGrowth]
      ,[NormalizedPEG]
      ,[EarningYield]
      ,[SalesYield]
      ,[BookValueYield]
      ,[CashFlowYield]
      ,[ForwardDividend]
      ,[WorkingCapitalPerShare]
      ,[WorkingCapitalPerShare3YrAvg]
      ,[WorkingCapitalPerShare5YrAvg]
      ,[BuyBackYield]
      ,[TotalYield]
      ,[PricetoEBITDA]
      ,[ForwardROE]
      ,[ForwardROA]
      ,[TwoYearsForwardEarningYield]
      ,[TwoYearsForwardPERatio]
      ,[TotalAssetPerShare]
      ,[EVtoRevenue]
      ,[EVtoPreTaxIncome]
      ,[EVtoTotalAssets]
      ,[EVtoFCF]
      ,[EVtoEBIT]
      ,[FFOPerShare]
      ,[PricetoCashRatio]
      ,[CAPERatio])
	ON TargetTable.[ExchangeId] = SourceTable.[ExchangeId]
	AND TargetTable.[Symbol] = SourceTable.[Symbol]
    AND TargetTable.[AsOfDate] = SourceTable.[AsOfDate]
	

	WHEN NOT MATCHED BY TARGET THEN
	INSERT(
      [MValuationRatioId]
      ,[CreatedDate]
      ,[UpdatedDate]
      ,[ExchangeId]
      ,[CompanyName]
      ,[Symbol]
      ,[CUSIP]
      ,[CIK]
      ,[ISIN]
      ,[SEDOL]
      ,[ShareClassId]
	  ,[AsOfDate]
      ,[SalesPerShare]
      ,[GrowthAnnSalesPerShare5Year]
      ,[BookValuePerShare]
      ,[CFPerShare]
      ,[FCFPerShare]
      ,[PriceToEPS]
      ,[RatioPE5YearHigh]
      ,[RatioPE5YearLow]
      ,[PriceToBook]
      ,[PriceToSales]
      ,[PriceToCashFlow]
      ,[PriceToFreeCashFlow]
      ,[DivRate]
      ,[DividendYield]
      ,[DivPayoutTotOps]
      ,[DivPayout5Year]
      ,[DivYield5Year]
      ,[PayoutRatio]
      ,[SustainableGrowthRate]
      ,[CashReturn]
      ,[ForwardEarningYield]
      ,[PEGRatio]
      ,[PEGPayback]
      ,[ForwardDividendYield]
      ,[ForwardPERatio]
      ,[TangibleBookValuePerShare]
      ,[TangibleBVPerShare3YrAvg]
      ,[TangibleBVPerShare5YrAvg]
      ,[EVToEBITDA]
      ,[RatioPE5YearAverage]
      ,[NormalizedPERatio]
      ,[FCFYield]
      ,[EVToForwardEBIT]
      ,[EVToForwardEBITDA]
      ,[EVToForwardRevenue]
      ,[TwoYearsEVToForwardEBIT]
      ,[TwoYearsEVToForwardEBITDA]
      ,[FirstYearEstimatedEPSGrowth]
      ,[SecondYearEstimatedEPSGrowth]
      ,[NormalizedPEG]
      ,[EarningYield]
      ,[SalesYield]
      ,[BookValueYield]
      ,[CashFlowYield]
      ,[ForwardDividend]
      ,[WorkingCapitalPerShare]
      ,[WorkingCapitalPerShare3YrAvg]
      ,[WorkingCapitalPerShare5YrAvg]
      ,[BuyBackYield]
      ,[TotalYield]
      ,[PricetoEBITDA]
      ,[ForwardROE]
      ,[ForwardROA]
      ,[TwoYearsForwardEarningYield]
      ,[TwoYearsForwardPERatio]
      ,[TotalAssetPerShare]
      ,[EVtoRevenue]
      ,[EVtoPreTaxIncome]
      ,[EVtoTotalAssets]
      ,[EVtoFCF]
      ,[EVtoEBIT]
      ,[FFOPerShare]
      ,[PricetoCashRatio]
      ,[CAPERatio]) 
	VALUES (NEWID()
		   ,GETUTCDATE()
		   ,GETUTCDATE()
		  ,[ExchangeId]
		  ,[CompanyName]
		  ,[Symbol]
		  ,[CUSIP]
		  ,[CIK]
		  ,[ISIN]
		  ,[SEDOL]
		  ,[ShareClassId]
		  ,[AsOfDate]
		  ,[SalesPerShare]
		  ,[GrowthAnnSalesPerShare5Year]
		  ,[BookValuePerShare]
		  ,[CFPerShare]
		  ,[FCFPerShare]
		  ,[PriceToEPS]
		  ,[RatioPE5YearHigh]
		  ,[RatioPE5YearLow]
		  ,[PriceToBook]
		  ,[PriceToSales]
		  ,[PriceToCashFlow]
		  ,[PriceToFreeCashFlow]
		  ,[DivRate]
		  ,[DividendYield]
		  ,[DivPayoutTotOps]
		  ,[DivPayout5Year]
		  ,[DivYield5Year]
		  ,[PayoutRatio]
		  ,[SustainableGrowthRate]
		  ,[CashReturn]
		  ,[ForwardEarningYield]
		  ,[PEGRatio]
		  ,[PEGPayback]
		  ,[ForwardDividendYield]
		  ,[ForwardPERatio]
		  ,[TangibleBookValuePerShare]
		  ,[TangibleBVPerShare3YrAvg]
		  ,[TangibleBVPerShare5YrAvg]
		  ,[EVToEBITDA]
		  ,[RatioPE5YearAverage]
		  ,[NormalizedPERatio]
		  ,[FCFYield]
		  ,[EVToForwardEBIT]
		  ,[EVToForwardEBITDA]
		  ,[EVToForwardRevenue]
		  ,[TwoYearsEVToForwardEBIT]
		  ,[TwoYearsEVToForwardEBITDA]
		  ,[FirstYearEstimatedEPSGrowth]
		  ,[SecondYearEstimatedEPSGrowth]
		  ,[NormalizedPEG]
		  ,[EarningYield]
		  ,[SalesYield]
		  ,[BookValueYield]
		  ,[CashFlowYield]
		  ,[ForwardDividend]
		  ,[WorkingCapitalPerShare]
		  ,[WorkingCapitalPerShare3YrAvg]
		  ,[WorkingCapitalPerShare5YrAvg]
		  ,[BuyBackYield]
		  ,[TotalYield]
		  ,[PricetoEBITDA]
		  ,[ForwardROE]
		  ,[ForwardROA]
		  ,[TwoYearsForwardEarningYield]
		  ,[TwoYearsForwardPERatio]
		  ,[TotalAssetPerShare]
		  ,[EVtoRevenue]
		  ,[EVtoPreTaxIncome]
		  ,[EVtoTotalAssets]
		  ,[EVtoFCF]
		  ,[EVtoEBIT]
		  ,[FFOPerShare]
		  ,[PricetoCashRatio]
		  ,[CAPERatio])

	OUTPUT $action INTO @SummaryOfChanges;

	UPDATE [dbo].[IngestionTasks]
	SET IsProcessed = 1
	WHERE IngestionTaskId IN (SELECT ID FROM @UnprocessedTasks);

	-- Query the results of the table variable.  
	SELECT Change, COUNT(*) AS CountPerChange  
	FROM @SummaryOfChanges  
	GROUP BY Change;

END
GO


