// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NachoTacos.Ingestion.MorningStar.Data;

namespace NachoTacos.Ingestion.MorningStar.Data.Migrations
{
    [DbContext(typeof(IngestionContext))]
    [Migration("20200106034915_add-table-mcompanyfinancial")]
    partial class addtablemcompanyfinancial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("NachoTacos.Ingestion.MorningStar.Domain.ChangeTable", b =>
                {
                    b.Property<string>("Change")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CountPerChange")
                        .HasColumnType("int");

                    b.ToTable("ChangeTables");
                });

            modelBuilder.Entity("NachoTacos.Ingestion.MorningStar.Domain.ClientConfiguration", b =>
                {
                    b.Property<Guid>("ClientConfigurationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AccountLogin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AccountPassword")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LoginUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ClientConfigurationId");

                    b.ToTable("ClientConfigurations");
                });

            modelBuilder.Entity("NachoTacos.Ingestion.MorningStar.Domain.IngestionTask", b =>
                {
                    b.Property<Guid>("IngestionTaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EndPoint")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsProcessed")
                        .HasColumnType("bit");

                    b.Property<string>("RequestJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("IngestionTaskId");

                    b.ToTable("IngestionTasks");
                });

            modelBuilder.Entity("NachoTacos.Ingestion.MorningStar.Domain.MCompanyFinancialAvailability", b =>
                {
                    b.Property<Guid>("MCompanyFinancialAvailabilityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CIK")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CUSIP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("End")
                        .HasColumnType("int");

                    b.Property<string>("ExchangeId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GlobalTemplateCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ISIN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IndustryGroupId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IndustryGroupName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IndustryId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IndustryName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LatestAnnualReportDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LatestPreliminaryReportDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LatestQuarterlyReportDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LatestSemiAnnualReportDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SEDOL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SectorId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SectorName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Start")
                        .HasColumnType("int");

                    b.Property<string>("Symbol")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TemplateCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("MCompanyFinancialAvailabilityId");

                    b.ToTable("MCompanyFinancialAvailability","MStar");
                });

            modelBuilder.Entity("NachoTacos.Ingestion.MorningStar.Domain.MStockExchangeSecurity", b =>
                {
                    b.Property<Guid>("MStockExchangeSecurityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CIK")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CUSIP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DelistingDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DelistingReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExchangeId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExchangeSubMarketGlobalId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ISIN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvestmentTypeId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ParValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SEDOL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StockStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SuspendedFlag")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Symbol")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("MStockExchangeSecurityId");

                    b.ToTable("MStockExchangeSecurity","MStar");
                });

            modelBuilder.Entity("NachoTacos.Ingestion.MorningStar.Domain.TBalanceSheet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AccessionNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("AccountsPayable")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("AccountsReceivable")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("AccruedInterestReceivable")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("AccruedInvestmentIncome")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("AccruedLiabilitiesTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("AccruedandDeferredIncome")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("AccruedandDeferredIncomeCurrent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("AccruedandDeferredIncomeNonCurrent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("AccumulatedDepreciation")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("AdditionalPaidInCapital")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("AdvanceFromFederalHomeLoanBanks")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("AdvancesfromCentralBanks")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("AllowanceForDoubtfulAccountsReceivable")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("AllowanceForLoansAndLeaseLosses")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("AllowanceForNotesReceivable")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("AssetsHeldForSale")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("AssetsHeldForSaleCurrent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("AssetsHeldForSaleNonCurrent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("AssetsOfDiscontinuedOperations")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("AssetsPledgedasCollateralSubjecttoSaleorRepledgingTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("AvailableForSaleSecurities")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("BankAcceptanceExecutedAndOutstanding")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("BankIndebtedness")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("BankLoan")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("BankLoansCurrent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("BankLoansNonCurrent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("BankLoansTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("BankOwnedLifeInsurance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("BiologicalAssets")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("BuildingsAndImprovements")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CapitalLeaseObligations")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CapitalStock")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Cash")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CashAndCashEquivalents")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CashAndDueFromBanks")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CashCashEquivalentsAndFederalFundsSold")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CashCashEquivalentsAndShortTermInvestments")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CashEquivalents")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CashRestrictedOrPledged")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CashValueOfLifeInsurance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CashandBalanceswithCentralBanks")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CasualtyClaims")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CededUnearnedPremiums")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CertificatesofDepositsandOtherDebtSecuritiesIssued")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ClaimsOutstanding")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CommercialLoan")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CommercialPaper")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CommonStock")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CommonStockEquity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CommonStocksAvailableForSale")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CommonUtilityPlant")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ConstructionGrants")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ConstructionInProgress")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ConsumerLoan")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ConvertibleLoansCurrent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ConvertibleLoansNonCurrent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ConvertibleLoansTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CurrencyId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("CurrentAccruedExpenses")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CurrentAssets")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CurrentCapitalLeaseObligation")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CurrentDebt")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CurrentDebtAndCapitalLeaseObligation")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CurrentDeferredAssets")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CurrentDeferredLiabilities")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CurrentDeferredRevenue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CurrentDeferredTaxesAssets")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CurrentDeferredTaxesLiabilities")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CurrentLiabilities")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CurrentNotesPayable")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CurrentOtherFinancialLiabilities")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CurrentProvisions")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CustomerAcceptances")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CustomerAccounts")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("DataType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("DebenturesandDebtCertificates")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DebtDueBeyond")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DebtDueInYear1")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DebtDueInYear2")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DebtDueInYear5")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DebtSecurities")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DebtSecuritiesinIssue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DebtTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DeferredAcquisitionCosts")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DeferredAssets")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DeferredCostCurrent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DeferredCosts")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DeferredFinancingCosts")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DeferredIncomeTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DeferredPolicyAcquisitionCosts")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DeferredTaxAssets")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DeferredTaxLiabilitiesTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DefinedPensionBenefit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DepositCertificates")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DepositsMadeunderAssumedReinsuranceContract")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DepositsReceivedunderCededInsuranceContract")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DepositsbyBank")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DerivativeAssets")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DerivativeProductLiabilities")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DividendsPayable")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DuefromRelatedPartiesCurrent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DuefromRelatedPartiesNonCurrent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DuetoRelatedParties")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DuetoRelatedPartiesCurrent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DuetoRelatedPartiesNonCurrent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ESOPDebtGuarantee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ElectricUtilityPlant")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("EmployeeBenefits")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("EquityInvestments")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("EquitySharesInvestments")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("FacilitiesAndOther")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("FederalFundsPurchased")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("FederalFundsPurchasedAndSecuritiesSoldUnderAgreementToRepurchase")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("FederalFundsSold")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("FederalFundsSoldAndSecuritiesPurchaseUnderAgreementsToResell")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("FederalHomeLoanBankStock")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("FileDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("FinanceLeaseReceivables")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("FinanceLeaseReceivablesCurrent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("FinanceLeaseReceivablesNonCurrent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("FinancialAssets")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("FinancialAssetsDesignatedasFairValueThroughProfitorLossTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("FinancialInstrumentsSoldUnderAgreementsToRepurchase")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("FinancialLiabilitiesCurrent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("FinancialLiabilitiesDesignatedasFairValueThroughProfitorLossTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("FinancialLiabilitiesMeasuredatAmortizedCostTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("FinancialLiabilitiesNonCurrent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("FinancialOrDerivativeInvestmentCurrentLiabilities")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("FinishedGoods")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("FiscalYearChange")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("FiscalYearEnd")
                        .HasColumnType("int");

                    b.Property<decimal>("FixedAssetsRevaluationReserve")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("FixedMaturitiesAvailableForSale")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("FixedMaturitiesHeldToMaturity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("FixedMaturitiesTrading")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("FixedMaturityInvestments")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("FlightFleetVehicleAndRelatedEquipments")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ForeclosedAssets")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ForeignComponent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ForeignCurrencyTranslationAdjustments")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("FormType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("FuelAndNaturalGas")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("FuturePolicyBenefits")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("GainsLossesNotAffectingRetainedEarnings")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("GeneralPartnershipCapital")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Goodwill")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("GoodwillAndOtherIntangibleAssets")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("GrossAccountsReceivable")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("GrossLoan")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("GrossNotesReceivable")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("GrossPPE")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("GuaranteedInvestmentContract")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("HedgingAssetsCurrent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("HedgingAssetsNonCurrent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("HedgingAssetsTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("HedgingLiabilitiesCurrent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("HedgingLiabilitiesNonCurrent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("HedgingLiabilitiesTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("HeldToMaturitySecurities")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("IncomeTaxPayable")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("IngestionTaskId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("InsuranceContractAssets")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("InsuranceContractLiabilities")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("InsuranceFundsCurrent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("InsuranceFundsNonCurrent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("InsurancePayables")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("InsuranceReceivables")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("InterestBearingBorrowingsCurrent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("InterestBearingBorrowingsNonCurrent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("InterestBearingBorrowingsTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("InterestBearingDepositsAssets")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("InterestBearingDepositsLiabilities")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("InterestPayable")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Interim")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("InventoriesAdjustmentsAllowances")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Inventory")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("InvestedCapital")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("InvestmentContractLiabilities")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("InvestmentProperties")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("InvestmentTaxCredits")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("InvestmentinFinancialAssets")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("InvestmentsAndAdvances")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("InvestmentsInAffiliatesSubsidiariesAssociatesAndJointVentures")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("InvestmentsInOtherVenturesUnderEquityMethod")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("InvestmentsInVariableInterestEntity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("InvestmentsinAssociatesatCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("InvestmentsinJointVenturesatCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("InvestmentsinSubsidiariesatCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ItemsinTheCourseofTransmissiontoOtherBanks")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("LandAndImprovements")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Leases")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("LiabilitiesHeldforSaleCurrent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("LiabilitiesHeldforSaleNonCurrent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("LiabilitiesHeldforSaleTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("LiabilitiesOfDiscontinuedOperations")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("LiabilitiesRecognizedforFairValueChangesinPortfolioHedgeofInterestRateRisk")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("LimitedPartnership")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("LimitedPartnershipCapital")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("LineOfCredit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("LoanAndLoanReceivables")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("LoanCapital")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("LoansHeldForSale")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("LoansReceivable")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("LoansandAdvancestoBank")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("LoansandAdvancestoCustomer")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("LongTermCapitalLeaseObligation")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("LongTermContracts")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("LongTermDebt")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("LongTermDebtAndCapitalLeaseObligation")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("LongTermEquityInvestment")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("LongTermProvisions")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MachineryFurnitureEquipment")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MaterialsAndSupplies")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MineralProperties")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MinimumPensionLiabilities")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MinorityInterest")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MoneyMarketInvestments")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MortgageAndConsumerloans")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MortgageLoan")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NaturalGasFuelAndOther")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NaturalResourceAssets")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NetAssets")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NetDebt")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NetLoan")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NetOtherUnrealizedGainLoss")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NetPPE")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NetTangibleAssets")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NetUnrealizedGainLossForeignCurrency")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NetUnrealizedGainLossInvestments")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NetUtilityPlant")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NonCurrentAccountsReceivable")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NonCurrentAccruedExpenses")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NonCurrentDeferredAssets")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NonCurrentDeferredLiabilities")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NonCurrentDeferredRevenue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NonCurrentDeferredTaxesAssets")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NonCurrentDeferredTaxesLiabilities")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NonCurrentNoteReceivables")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NonCurrentOtherFinancialLiabilities")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NonCurrentPensionAndOtherPostretirementBenefitPlans")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NonCurrentPrepaidAssets")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NonInterestBearingBorrowingsCurrent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NonInterestBearingBorrowingsNonCurrent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NonInterestBearingBorrowingsTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NonInterestBearingDeposits")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NotesReceivable")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OperatingLeaseAssets")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OrdinarySharesNumber")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OtherAssets")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OtherBorrowedFunds")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OtherCapitalStock")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OtherCurrentAssets")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OtherCurrentBorrowings")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OtherCurrentLiabilities")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OtherDeferredCosts")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OtherDeposits")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OtherEquityAdjustments")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OtherEquityInterest")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OtherFinancialLiabilities")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OtherIntangibleAssets")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OtherInterestEarningAssets")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OtherInventories")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OtherInvestedAssets")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OtherInvestments")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OtherLiabilities")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OtherLoanAssets")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OtherLoansCurrent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OtherLoansNonCurrent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OtherLoansTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OtherNonCurrentAssets")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OtherNonCurrentLiabilities")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OtherPayable")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OtherProperties")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OtherRealEstateOwned")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OtherReceivables")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OtherReserves")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ParticipatingPolicyholderEquity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Patents")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Payables")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PayablesAndAccruedExpenses")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PaymentofBills")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PensionAndOtherPostretirementBenefitPlansTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PensionandOtherPostRetirementBenefitPlansCurrent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("PeriodEndingDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("PlacementwithBanksandOtherFinancialInstitutions")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PolicyLoans")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PolicyholderFunds")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PreferredSecuritiesOutsideStockEquity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PreferredSharesNumber")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PreferredStock")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PreferredStockEquity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PreferredStockOfSubsidiary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PreferredStocksAvailableForSale")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PremiumsReceivable")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PrepaidAssets")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PrepaidReinsurancePremiums")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Properties")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ProvisionsTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PurchasedComponents")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("RawMaterials")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("RealEstate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("RealEstateAndRealEstateJointVenturesHeldForInvestment")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("RealEstateHeldForSale")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Receivables")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("RecievablesAdjustmentsAllowances")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("RedeemablePreferredStock")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("RegulatoryAssets")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("RegulatoryLiabilities")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ReinsuranceAssets")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ReinsuranceBalancesPayable")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ReinsuranceReceivables")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ReinsuranceRecoverable")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ReinsuranceRecoverableForPaidLosses")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ReinsuranceRecoverableForUnpaidLosses")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ReinsuranceShareofAccruedPolicyholderClaims")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ReinsuranceShareofInsuranceContract")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("ReportDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("RestrictedCash")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("RestrictedCashAndCashEquivalents")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("RestrictedCashAndInvestments")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("RestrictedCommonStock")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("RestrictedInvestments")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("RetainedEarnings")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SecuritiesAndInvestments")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SecuritiesLendingCollateral")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SecuritiesLendingPayable")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SecuritiesLoaned")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SecurityAgreeToBeResell")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SecurityBorrowed")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SecuritySoldNotYetRepurchased")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SeparateAccountAssets")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SeparateAccountLiability")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ShortTermInvestments")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ShortTermInvestmentsAvailableForSale")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ShortTermInvestmentsHeldToMaturity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ShortTermInvestmentsTrading")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("StatementType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("StockholdersEquity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("StudentLoan")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SubordinatedLiabilities")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TangibleBookValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TaxAssetsTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TaxesAssetsCurrent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TaxesReceivable")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TimeDepositsPlaced")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalAssets")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalCapitalization")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalDebt")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalDebtInMaturitySchedule")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalDeferredCreditsAndOtherNonCurrentLiabilities")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalDeposits")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalEquity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalEquityAsReported")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalEquityGrossMinorityInterest")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalFinancialLeaseObligations")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalInvestments")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalLiabilities")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalLiabilitiesAsReported")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalLiabilitiesNetMinorityInterest")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalNonCurrentAssets")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalNonCurrentLiabilities")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalNonCurrentLiabilitiesNetMinorityInterest")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalPartnershipCapital")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalPolicyHoldersLiabilities")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalTaxPayable")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TradeAndOtherReceivablesNonCurrent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TradeandOtherPayablesNonCurrent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TradingAndOtherReceivable")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TradingAssets")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TradingLiabilities")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TradingSecurities")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TradingandFinancialLiabilities")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TreasuryBillsandOtherEligibleBills")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TreasurySharesNumber")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TreasuryStock")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TrustPreferredSecurities")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnallocatedSurplus")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnbilledReceivables")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnclassifiedCurrentAssets")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnearnedIncome")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnearnedPremiums")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnpaidLossAndLossReserve")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnrealizedGainLoss")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("WaterProduction")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("WorkInProcess")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("WorkingCapital")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("TBalanceSheet","MStar");
                });

            modelBuilder.Entity("NachoTacos.Ingestion.MorningStar.Domain.TCompanyFinancialAvailability", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CIK")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CUSIP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("End")
                        .HasColumnType("int");

                    b.Property<string>("ExchangeId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GlobalTemplateCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ISIN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IndustryGroupId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IndustryGroupName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IndustryId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IndustryName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("IngestionTaskId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("LatestAnnualReportDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LatestPreliminaryReportDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LatestQuarterlyReportDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LatestSemiAnnualReportDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SEDOL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SectorId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SectorName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Start")
                        .HasColumnType("int");

                    b.Property<string>("Symbol")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TemplateCode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TCompanyFinancialAvailability","MStar");
                });

            modelBuilder.Entity("NachoTacos.Ingestion.MorningStar.Domain.TGeneralInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CIK")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CUSIP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExchangeId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ISIN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("IngestionTaskId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SEDOL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShareClassId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Symbol")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TGeneralInfo","MStar");
                });

            modelBuilder.Entity("NachoTacos.Ingestion.MorningStar.Domain.TStockExchangeSecurity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CIK")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CUSIP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DelistingDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DelistingReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExchangeId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExchangeSubMarketGlobalId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ISIN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("IngestionTaskId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("InvestmentTypeId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ParValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SEDOL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StockStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SuspendedFlag")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Symbol")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TStockExchangeSecurity","MStar");
                });
#pragma warning restore 612, 618
        }
    }
}
