using System;
using Microsoft.EntityFrameworkCore.Migrations;

namespace NachoTacos.Ingestion.MorningStar.Data.Migrations
{
    public partial class initial : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.EnsureSchema(
                name: "MStar");

            migrationBuilder.CreateTable(
                name: "ClientConfigurations",
                columns: table => new
                {
                    ClientConfigurationId = table.Column<Guid>(nullable: false),
                    AccountLogin = table.Column<string>(nullable: true),
                    AccountPassword = table.Column<string>(nullable: true),
                    LoginUrl = table.Column<string>(nullable: true),
                    IsActive = table.Column<bool>(nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_ClientConfigurations", x => x.ClientConfigurationId);
                });

            migrationBuilder.CreateTable(
                name: "IngestionTasks",
                columns: table => new
                {
                    IngestionTaskId = table.Column<Guid>(nullable: false),
                    CreatedDate = table.Column<DateTime>(nullable: false),
                    UpdatedDate = table.Column<DateTime>(nullable: false),
                    Entity = table.Column<string>(nullable: true),
                    RequestJson = table.Column<string>(nullable: true),
                    IsProcessed = table.Column<bool>(nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_IngestionTasks", x => x.IngestionTaskId);
                });

            migrationBuilder.CreateTable(
                name: "TBalanceSheet",
                schema: "MStar",
                columns: table => new
                {
                    Id = table.Column<Guid>(nullable: false),
                    IngestionTaskId = table.Column<Guid>(nullable: false),
                    ReportDate = table.Column<DateTime>(nullable: false),
                    PeriodEndingDate = table.Column<DateTime>(nullable: false),
                    FileDate = table.Column<DateTime>(nullable: false),
                    StatementType = table.Column<string>(nullable: true),
                    DataType = table.Column<string>(nullable: true),
                    Interim = table.Column<string>(nullable: true),
                    CurrencyId = table.Column<string>(nullable: true),
                    FiscalYearEnd = table.Column<int>(nullable: false),
                    AccountsPayable = table.Column<decimal>(nullable: false),
                    AccountsReceivable = table.Column<decimal>(nullable: false),
                    GrossAccountsReceivable = table.Column<decimal>(nullable: false),
                    NonCurrentAccountsReceivable = table.Column<decimal>(nullable: false),
                    CurrentAccruedExpenses = table.Column<decimal>(nullable: false),
                    NonCurrentAccruedExpenses = table.Column<decimal>(nullable: false),
                    AccruedInterestReceivable = table.Column<decimal>(nullable: false),
                    AccruedInvestmentIncome = table.Column<decimal>(nullable: false),
                    AccumulatedDepreciation = table.Column<decimal>(nullable: false),
                    GainsLossesNotAffectingRetainedEarnings = table.Column<decimal>(nullable: false),
                    AdditionalPaidInCapital = table.Column<decimal>(nullable: false),
                    AdvanceFromFederalHomeLoanBanks = table.Column<decimal>(nullable: false),
                    AllowanceForDoubtfulAccountsReceivable = table.Column<decimal>(nullable: false),
                    AllowanceForLoansAndLeaseLosses = table.Column<decimal>(nullable: false),
                    AllowanceForNotesReceivable = table.Column<decimal>(nullable: false),
                    AssetsHeldForSale = table.Column<decimal>(nullable: false),
                    AssetsOfDiscontinuedOperations = table.Column<decimal>(nullable: false),
                    AvailableForSaleSecurities = table.Column<decimal>(nullable: false),
                    BankAcceptanceExecutedAndOutstanding = table.Column<decimal>(nullable: false),
                    BankIndebtedness = table.Column<decimal>(nullable: false),
                    BankLoan = table.Column<decimal>(nullable: false),
                    BankOwnedLifeInsurance = table.Column<decimal>(nullable: false),
                    SecurityBorrowed = table.Column<decimal>(nullable: false),
                    BuildingsAndImprovements = table.Column<decimal>(nullable: false),
                    CapitalStock = table.Column<decimal>(nullable: false),
                    Cash = table.Column<decimal>(nullable: false),
                    CashEquivalents = table.Column<decimal>(nullable: false),
                    CashAndCashEquivalents = table.Column<decimal>(nullable: false),
                    CashAndDueFromBanks = table.Column<decimal>(nullable: false),
                    CashCashEquivalentsAndFederalFundsSold = table.Column<decimal>(nullable: false),
                    CashCashEquivalentsAndShortTermInvestments = table.Column<decimal>(nullable: false),
                    CasualtyClaims = table.Column<decimal>(nullable: false),
                    CededUnearnedPremiums = table.Column<decimal>(nullable: false),
                    CommercialLoan = table.Column<decimal>(nullable: false),
                    CommercialPaper = table.Column<decimal>(nullable: false),
                    CommonStock = table.Column<decimal>(nullable: false),
                    CommonStockEquity = table.Column<decimal>(nullable: false),
                    CommonStocksAvailableForSale = table.Column<decimal>(nullable: false),
                    ConstructionInProgress = table.Column<decimal>(nullable: false),
                    ConsumerLoan = table.Column<decimal>(nullable: false),
                    MinimumPensionLiabilities = table.Column<decimal>(nullable: false),
                    CurrentAssets = table.Column<decimal>(nullable: false),
                    CurrentDebt = table.Column<decimal>(nullable: false),
                    CurrentDebtAndCapitalLeaseObligation = table.Column<decimal>(nullable: false),
                    CurrentLiabilities = table.Column<decimal>(nullable: false),
                    CurrentCapitalLeaseObligation = table.Column<decimal>(nullable: false),
                    CustomerAcceptances = table.Column<decimal>(nullable: false),
                    DeferredAcquisitionCosts = table.Column<decimal>(nullable: false),
                    DeferredAssets = table.Column<decimal>(nullable: false),
                    DeferredCosts = table.Column<decimal>(nullable: false),
                    DeferredFinancingCosts = table.Column<decimal>(nullable: false),
                    NonCurrentDeferredLiabilities = table.Column<decimal>(nullable: false),
                    CurrentDeferredLiabilities = table.Column<decimal>(nullable: false),
                    DeferredPolicyAcquisitionCosts = table.Column<decimal>(nullable: false),
                    CurrentDeferredRevenue = table.Column<decimal>(nullable: false),
                    NonCurrentDeferredRevenue = table.Column<decimal>(nullable: false),
                    DeferredTaxAssets = table.Column<decimal>(nullable: false),
                    CurrentDeferredTaxesAssets = table.Column<decimal>(nullable: false),
                    CurrentDeferredTaxesLiabilities = table.Column<decimal>(nullable: false),
                    NonCurrentDeferredTaxesAssets = table.Column<decimal>(nullable: false),
                    NonCurrentDeferredTaxesLiabilities = table.Column<decimal>(nullable: false),
                    DefinedPensionBenefit = table.Column<decimal>(nullable: false),
                    DerivativeProductLiabilities = table.Column<decimal>(nullable: false),
                    DerivativeAssets = table.Column<decimal>(nullable: false),
                    DividendsPayable = table.Column<decimal>(nullable: false),
                    ESOPDebtGuarantee = table.Column<decimal>(nullable: false),
                    EmployeeBenefits = table.Column<decimal>(nullable: false),
                    EquityInvestments = table.Column<decimal>(nullable: false),
                    FacilitiesAndOther = table.Column<decimal>(nullable: false),
                    FederalFundsPurchased = table.Column<decimal>(nullable: false),
                    FederalFundsPurchasedAndSecuritiesSoldUnderAgreementToRepurchase = table.Column<decimal>(nullable: false),
                    FederalFundsSold = table.Column<decimal>(nullable: false),
                    FederalFundsSoldAndSecuritiesPurchaseUnderAgreementsToResell = table.Column<decimal>(nullable: false),
                    FederalHomeLoanBankStock = table.Column<decimal>(nullable: false),
                    FinancialAssets = table.Column<decimal>(nullable: false),
                    FinancialInstrumentsSoldUnderAgreementsToRepurchase = table.Column<decimal>(nullable: false),
                    FinishedGoods = table.Column<decimal>(nullable: false),
                    FixedMaturitiesAvailableForSale = table.Column<decimal>(nullable: false),
                    FixedMaturitiesHeldToMaturity = table.Column<decimal>(nullable: false),
                    FixedMaturitiesTrading = table.Column<decimal>(nullable: false),
                    FixedMaturityInvestments = table.Column<decimal>(nullable: false),
                    FlightFleetVehicleAndRelatedEquipments = table.Column<decimal>(nullable: false),
                    ForeclosedAssets = table.Column<decimal>(nullable: false),
                    ForeignComponent = table.Column<decimal>(nullable: false),
                    ForeignCurrencyTranslationAdjustments = table.Column<decimal>(nullable: false),
                    FuelAndNaturalGas = table.Column<decimal>(nullable: false),
                    FuturePolicyBenefits = table.Column<decimal>(nullable: false),
                    GeneralPartnershipCapital = table.Column<decimal>(nullable: false),
                    Goodwill = table.Column<decimal>(nullable: false),
                    GoodwillAndOtherIntangibleAssets = table.Column<decimal>(nullable: false),
                    GrossLoan = table.Column<decimal>(nullable: false),
                    GrossPPE = table.Column<decimal>(nullable: false),
                    GuaranteedInvestmentContract = table.Column<decimal>(nullable: false),
                    HeldToMaturitySecurities = table.Column<decimal>(nullable: false),
                    IncomeTaxPayable = table.Column<decimal>(nullable: false),
                    InterestBearingDepositsLiabilities = table.Column<decimal>(nullable: false),
                    InterestPayable = table.Column<decimal>(nullable: false),
                    InterestBearingDepositsAssets = table.Column<decimal>(nullable: false),
                    Inventory = table.Column<decimal>(nullable: false),
                    InventoriesAdjustmentsAllowances = table.Column<decimal>(nullable: false),
                    InvestmentTaxCredits = table.Column<decimal>(nullable: false),
                    InvestmentsAndAdvances = table.Column<decimal>(nullable: false),
                    InvestmentsInAffiliatesSubsidiariesAssociatesAndJointVentures = table.Column<decimal>(nullable: false),
                    InvestmentsInOtherVenturesUnderEquityMethod = table.Column<decimal>(nullable: false),
                    InvestmentsInVariableInterestEntity = table.Column<decimal>(nullable: false),
                    LandAndImprovements = table.Column<decimal>(nullable: false),
                    Leases = table.Column<decimal>(nullable: false),
                    LiabilitiesOfDiscontinuedOperations = table.Column<decimal>(nullable: false),
                    LimitedPartnershipCapital = table.Column<decimal>(nullable: false),
                    LimitedPartnership = table.Column<decimal>(nullable: false),
                    LineOfCredit = table.Column<decimal>(nullable: false),
                    LoansHeldForSale = table.Column<decimal>(nullable: false),
                    LoansReceivable = table.Column<decimal>(nullable: false),
                    LongTermDebt = table.Column<decimal>(nullable: false),
                    LongTermDebtAndCapitalLeaseObligation = table.Column<decimal>(nullable: false),
                    LongTermEquityInvestment = table.Column<decimal>(nullable: false),
                    LongTermCapitalLeaseObligation = table.Column<decimal>(nullable: false),
                    MachineryFurnitureEquipment = table.Column<decimal>(nullable: false),
                    MaterialsAndSupplies = table.Column<decimal>(nullable: false),
                    MineralProperties = table.Column<decimal>(nullable: false),
                    MinorityInterest = table.Column<decimal>(nullable: false),
                    MoneyMarketInvestments = table.Column<decimal>(nullable: false),
                    MortgageLoan = table.Column<decimal>(nullable: false),
                    MortgageAndConsumerloans = table.Column<decimal>(nullable: false),
                    NaturalResourceAssets = table.Column<decimal>(nullable: false),
                    NetLoan = table.Column<decimal>(nullable: false),
                    NetOtherUnrealizedGainLoss = table.Column<decimal>(nullable: false),
                    NetPPE = table.Column<decimal>(nullable: false),
                    NetUnrealizedGainLossForeignCurrency = table.Column<decimal>(nullable: false),
                    NetUnrealizedGainLossInvestments = table.Column<decimal>(nullable: false),
                    NonInterestBearingDeposits = table.Column<decimal>(nullable: false),
                    CurrentNotesPayable = table.Column<decimal>(nullable: false),
                    NotesReceivable = table.Column<decimal>(nullable: false),
                    GrossNotesReceivable = table.Column<decimal>(nullable: false),
                    NonCurrentNoteReceivables = table.Column<decimal>(nullable: false),
                    OtherAssets = table.Column<decimal>(nullable: false),
                    OtherCapitalStock = table.Column<decimal>(nullable: false),
                    OtherCurrentAssets = table.Column<decimal>(nullable: false),
                    OtherCurrentBorrowings = table.Column<decimal>(nullable: false),
                    OtherCurrentLiabilities = table.Column<decimal>(nullable: false),
                    OtherDeferredCosts = table.Column<decimal>(nullable: false),
                    OtherDeposits = table.Column<decimal>(nullable: false),
                    OtherEquityAdjustments = table.Column<decimal>(nullable: false),
                    OtherIntangibleAssets = table.Column<decimal>(nullable: false),
                    OtherInterestEarningAssets = table.Column<decimal>(nullable: false),
                    OtherInventories = table.Column<decimal>(nullable: false),
                    OtherInvestedAssets = table.Column<decimal>(nullable: false),
                    OtherNonCurrentAssets = table.Column<decimal>(nullable: false),
                    OtherProperties = table.Column<decimal>(nullable: false),
                    OtherRealEstateOwned = table.Column<decimal>(nullable: false),
                    OtherReceivables = table.Column<decimal>(nullable: false),
                    ShortTermInvestments = table.Column<decimal>(nullable: false),
                    Patents = table.Column<decimal>(nullable: false),
                    Payables = table.Column<decimal>(nullable: false),
                    PayablesAndAccruedExpenses = table.Column<decimal>(nullable: false),
                    NonCurrentPensionAndOtherPostretirementBenefitPlans = table.Column<decimal>(nullable: false),
                    PolicyLoans = table.Column<decimal>(nullable: false),
                    TotalPolicyHoldersLiabilities = table.Column<decimal>(nullable: false),
                    PolicyholderFunds = table.Column<decimal>(nullable: false),
                    PreferredSecuritiesOutsideStockEquity = table.Column<decimal>(nullable: false),
                    TrustPreferredSecurities = table.Column<decimal>(nullable: false),
                    PreferredStock = table.Column<decimal>(nullable: false),
                    PreferredStockEquity = table.Column<decimal>(nullable: false),
                    PreferredStockOfSubsidiary = table.Column<decimal>(nullable: false),
                    PreferredStocksAvailableForSale = table.Column<decimal>(nullable: false),
                    PremiumsReceivable = table.Column<decimal>(nullable: false),
                    PrepaidAssets = table.Column<decimal>(nullable: false),
                    NonCurrentPrepaidAssets = table.Column<decimal>(nullable: false),
                    PrepaidReinsurancePremiums = table.Column<decimal>(nullable: false),
                    Properties = table.Column<decimal>(nullable: false),
                    CurrentProvisions = table.Column<decimal>(nullable: false),
                    LongTermProvisions = table.Column<decimal>(nullable: false),
                    PurchasedComponents = table.Column<decimal>(nullable: false),
                    RawMaterials = table.Column<decimal>(nullable: false),
                    RealEstateHeldForSale = table.Column<decimal>(nullable: false),
                    RealEstateAndRealEstateJointVenturesHeldForInvestment = table.Column<decimal>(nullable: false),
                    Receivables = table.Column<decimal>(nullable: false),
                    RecievablesAdjustmentsAllowances = table.Column<decimal>(nullable: false),
                    RedeemablePreferredStock = table.Column<decimal>(nullable: false),
                    RegulatoryAssets = table.Column<decimal>(nullable: false),
                    RegulatoryLiabilities = table.Column<decimal>(nullable: false),
                    ReinsuranceBalancesPayable = table.Column<decimal>(nullable: false),
                    ReinsuranceReceivables = table.Column<decimal>(nullable: false),
                    ReinsuranceRecoverable = table.Column<decimal>(nullable: false),
                    ReinsuranceRecoverableForPaidLosses = table.Column<decimal>(nullable: false),
                    ReinsuranceRecoverableForUnpaidLosses = table.Column<decimal>(nullable: false),
                    RestrictedCash = table.Column<decimal>(nullable: false),
                    RestrictedCashAndCashEquivalents = table.Column<decimal>(nullable: false),
                    RestrictedCashAndInvestments = table.Column<decimal>(nullable: false),
                    RestrictedCommonStock = table.Column<decimal>(nullable: false),
                    RestrictedInvestments = table.Column<decimal>(nullable: false),
                    RetainedEarnings = table.Column<decimal>(nullable: false),
                    SecuritiesLendingCollateral = table.Column<decimal>(nullable: false),
                    SecuritiesLendingPayable = table.Column<decimal>(nullable: false),
                    SecurityAgreeToBeResell = table.Column<decimal>(nullable: false),
                    SecuritySoldNotYetRepurchased = table.Column<decimal>(nullable: false),
                    SeparateAccountAssets = table.Column<decimal>(nullable: false),
                    SeparateAccountLiability = table.Column<decimal>(nullable: false),
                    ShortTermInvestmentsAvailableForSale = table.Column<decimal>(nullable: false),
                    ShortTermInvestmentsHeldToMaturity = table.Column<decimal>(nullable: false),
                    ShortTermInvestmentsTrading = table.Column<decimal>(nullable: false),
                    StockholdersEquity = table.Column<decimal>(nullable: false),
                    StudentLoan = table.Column<decimal>(nullable: false),
                    TotalTaxPayable = table.Column<decimal>(nullable: false),
                    TaxesReceivable = table.Column<decimal>(nullable: false),
                    TimeDepositsPlaced = table.Column<decimal>(nullable: false),
                    TotalAssets = table.Column<decimal>(nullable: false),
                    TotalCapitalization = table.Column<decimal>(nullable: false),
                    TotalDeferredCreditsAndOtherNonCurrentLiabilities = table.Column<decimal>(nullable: false),
                    TotalDeposits = table.Column<decimal>(nullable: false),
                    TotalInvestments = table.Column<decimal>(nullable: false),
                    TotalLiabilities = table.Column<decimal>(nullable: false),
                    TotalNonCurrentAssets = table.Column<decimal>(nullable: false),
                    TotalNonCurrentLiabilities = table.Column<decimal>(nullable: false),
                    TotalPartnershipCapital = table.Column<decimal>(nullable: false),
                    TradingAssets = table.Column<decimal>(nullable: false),
                    TradingLiabilities = table.Column<decimal>(nullable: false),
                    TradingSecurities = table.Column<decimal>(nullable: false),
                    TreasuryStock = table.Column<decimal>(nullable: false),
                    UnbilledReceivables = table.Column<decimal>(nullable: false),
                    UnearnedIncome = table.Column<decimal>(nullable: false),
                    UnearnedPremiums = table.Column<decimal>(nullable: false),
                    UnpaidLossAndLossReserve = table.Column<decimal>(nullable: false),
                    UnrealizedGainLoss = table.Column<decimal>(nullable: false),
                    WorkInProcess = table.Column<decimal>(nullable: false),
                    OtherNonCurrentLiabilities = table.Column<decimal>(nullable: false),
                    CapitalLeaseObligations = table.Column<decimal>(nullable: false),
                    OtherLiabilities = table.Column<decimal>(nullable: false),
                    OtherPayable = table.Column<decimal>(nullable: false),
                    InvestedCapital = table.Column<decimal>(nullable: false),
                    TangibleBookValue = table.Column<decimal>(nullable: false),
                    TotalEquity = table.Column<decimal>(nullable: false),
                    WorkingCapital = table.Column<decimal>(nullable: false),
                    TotalDebt = table.Column<decimal>(nullable: false),
                    CashValueOfLifeInsurance = table.Column<decimal>(nullable: false),
                    CommonUtilityPlant = table.Column<decimal>(nullable: false),
                    CurrentDeferredAssets = table.Column<decimal>(nullable: false),
                    NonCurrentDeferredAssets = table.Column<decimal>(nullable: false),
                    ElectricUtilityPlant = table.Column<decimal>(nullable: false),
                    NaturalGasFuelAndOther = table.Column<decimal>(nullable: false),
                    NetUtilityPlant = table.Column<decimal>(nullable: false),
                    WaterProduction = table.Column<decimal>(nullable: false),
                    SecuritiesAndInvestments = table.Column<decimal>(nullable: false),
                    OrdinarySharesNumber = table.Column<decimal>(nullable: false),
                    PreferredSharesNumber = table.Column<decimal>(nullable: false),
                    TreasurySharesNumber = table.Column<decimal>(nullable: false),
                    TotalLiabilitiesNetMinorityInterest = table.Column<decimal>(nullable: false),
                    TotalNonCurrentLiabilitiesNetMinorityInterest = table.Column<decimal>(nullable: false),
                    TotalEquityGrossMinorityInterest = table.Column<decimal>(nullable: false),
                    TradingAndOtherReceivable = table.Column<decimal>(nullable: false),
                    AccessionNumber = table.Column<string>(nullable: true),
                    FormType = table.Column<string>(nullable: true),
                    SecuritiesLoaned = table.Column<decimal>(nullable: false),
                    ParticipatingPolicyholderEquity = table.Column<decimal>(nullable: false),
                    NetTangibleAssets = table.Column<decimal>(nullable: false),
                    DuefromRelatedPartiesCurrent = table.Column<decimal>(nullable: false),
                    DuefromRelatedPartiesNonCurrent = table.Column<decimal>(nullable: false),
                    DuetoRelatedParties = table.Column<decimal>(nullable: false),
                    DuetoRelatedPartiesCurrent = table.Column<decimal>(nullable: false),
                    DuetoRelatedPartiesNonCurrent = table.Column<decimal>(nullable: false),
                    NetAssets = table.Column<decimal>(nullable: false),
                    InvestmentProperties = table.Column<decimal>(nullable: false),
                    InvestmentsinSubsidiariesatCost = table.Column<decimal>(nullable: false),
                    InvestmentsinAssociatesatCost = table.Column<decimal>(nullable: false),
                    InvestmentsinJointVenturesatCost = table.Column<decimal>(nullable: false),
                    InvestmentinFinancialAssets = table.Column<decimal>(nullable: false),
                    FinanceLeaseReceivables = table.Column<decimal>(nullable: false),
                    ConvertibleLoansCurrent = table.Column<decimal>(nullable: false),
                    BankLoansCurrent = table.Column<decimal>(nullable: false),
                    OtherLoansCurrent = table.Column<decimal>(nullable: false),
                    AccruedandDeferredIncome = table.Column<decimal>(nullable: false),
                    BankLoansNonCurrent = table.Column<decimal>(nullable: false),
                    OtherLoansNonCurrent = table.Column<decimal>(nullable: false),
                    OtherReserves = table.Column<decimal>(nullable: false),
                    LoansandAdvancestoBank = table.Column<decimal>(nullable: false),
                    LoansandAdvancestoCustomer = table.Column<decimal>(nullable: false),
                    TreasuryBillsandOtherEligibleBills = table.Column<decimal>(nullable: false),
                    EquitySharesInvestments = table.Column<decimal>(nullable: false),
                    DepositsbyBank = table.Column<decimal>(nullable: false),
                    CustomerAccounts = table.Column<decimal>(nullable: false),
                    ItemsinTheCourseofTransmissiontoOtherBanks = table.Column<decimal>(nullable: false),
                    TradingandFinancialLiabilities = table.Column<decimal>(nullable: false),
                    DebtSecuritiesinIssue = table.Column<decimal>(nullable: false),
                    SubordinatedLiabilities = table.Column<decimal>(nullable: false),
                    ProvisionsTotal = table.Column<decimal>(nullable: false),
                    OperatingLeaseAssets = table.Column<decimal>(nullable: false),
                    ClaimsOutstanding = table.Column<decimal>(nullable: false),
                    LongTermContracts = table.Column<decimal>(nullable: false),
                    RealEstate = table.Column<decimal>(nullable: false),
                    PaymentofBills = table.Column<decimal>(nullable: false),
                    LiabilitiesHeldforSaleCurrent = table.Column<decimal>(nullable: false),
                    LiabilitiesHeldforSaleNonCurrent = table.Column<decimal>(nullable: false),
                    UnclassifiedCurrentAssets = table.Column<decimal>(nullable: false),
                    DebtSecurities = table.Column<decimal>(nullable: false),
                    TotalFinancialLeaseObligations = table.Column<decimal>(nullable: false),
                    AccruedandDeferredIncomeCurrent = table.Column<decimal>(nullable: false),
                    AccruedandDeferredIncomeNonCurrent = table.Column<decimal>(nullable: false),
                    FinanceLeaseReceivablesCurrent = table.Column<decimal>(nullable: false),
                    FinanceLeaseReceivablesNonCurrent = table.Column<decimal>(nullable: false),
                    FinancialLiabilitiesCurrent = table.Column<decimal>(nullable: false),
                    FinancialLiabilitiesNonCurrent = table.Column<decimal>(nullable: false),
                    FinancialAssetsDesignatedasFairValueThroughProfitorLossTotal = table.Column<decimal>(nullable: false),
                    TaxesAssetsCurrent = table.Column<decimal>(nullable: false),
                    OtherEquityInterest = table.Column<decimal>(nullable: false),
                    InterestBearingBorrowingsNonCurrent = table.Column<decimal>(nullable: false),
                    NonInterestBearingBorrowingsNonCurrent = table.Column<decimal>(nullable: false),
                    TradeandOtherPayablesNonCurrent = table.Column<decimal>(nullable: false),
                    InterestBearingBorrowingsCurrent = table.Column<decimal>(nullable: false),
                    NonInterestBearingBorrowingsCurrent = table.Column<decimal>(nullable: false),
                    PensionandOtherPostRetirementBenefitPlansCurrent = table.Column<decimal>(nullable: false),
                    CashandBalanceswithCentralBanks = table.Column<decimal>(nullable: false),
                    PlacementwithBanksandOtherFinancialInstitutions = table.Column<decimal>(nullable: false),
                    OtherLoanAssets = table.Column<decimal>(nullable: false),
                    HedgingAssetsTotal = table.Column<decimal>(nullable: false),
                    AssetsPledgedasCollateralSubjecttoSaleorRepledgingTotal = table.Column<decimal>(nullable: false),
                    TaxAssetsTotal = table.Column<decimal>(nullable: false),
                    AdvancesfromCentralBanks = table.Column<decimal>(nullable: false),
                    CertificatesofDepositsandOtherDebtSecuritiesIssued = table.Column<decimal>(nullable: false),
                    DepositCertificates = table.Column<decimal>(nullable: false),
                    DebenturesandDebtCertificates = table.Column<decimal>(nullable: false),
                    InterestBearingBorrowingsTotal = table.Column<decimal>(nullable: false),
                    NonInterestBearingBorrowingsTotal = table.Column<decimal>(nullable: false),
                    OtherBorrowedFunds = table.Column<decimal>(nullable: false),
                    FinancialLiabilitiesDesignatedasFairValueThroughProfitorLossTotal = table.Column<decimal>(nullable: false),
                    FinancialLiabilitiesMeasuredatAmortizedCostTotal = table.Column<decimal>(nullable: false),
                    LoanCapital = table.Column<decimal>(nullable: false),
                    HedgingLiabilitiesTotal = table.Column<decimal>(nullable: false),
                    LiabilitiesRecognizedforFairValueChangesinPortfolioHedgeofInterestRateRisk = table.Column<decimal>(nullable: false),
                    AccruedLiabilitiesTotal = table.Column<decimal>(nullable: false),
                    DeferredIncomeTotal = table.Column<decimal>(nullable: false),
                    DeferredTaxLiabilitiesTotal = table.Column<decimal>(nullable: false),
                    ReinsuranceAssets = table.Column<decimal>(nullable: false),
                    ReinsuranceShareofInsuranceContract = table.Column<decimal>(nullable: false),
                    ReinsuranceShareofAccruedPolicyholderClaims = table.Column<decimal>(nullable: false),
                    DepositsMadeunderAssumedReinsuranceContract = table.Column<decimal>(nullable: false),
                    InsuranceContractAssets = table.Column<decimal>(nullable: false),
                    InsuranceReceivables = table.Column<decimal>(nullable: false),
                    InsuranceContractLiabilities = table.Column<decimal>(nullable: false),
                    InsurancePayables = table.Column<decimal>(nullable: false),
                    DepositsReceivedunderCededInsuranceContract = table.Column<decimal>(nullable: false),
                    InvestmentContractLiabilities = table.Column<decimal>(nullable: false),
                    ConstructionGrants = table.Column<decimal>(nullable: false),
                    DeferredCostCurrent = table.Column<decimal>(nullable: false),
                    PensionAndOtherPostretirementBenefitPlansTotal = table.Column<decimal>(nullable: false),
                    LiabilitiesHeldforSaleTotal = table.Column<decimal>(nullable: false),
                    HedgingAssetsNonCurrent = table.Column<decimal>(nullable: false),
                    HedgingAssetsCurrent = table.Column<decimal>(nullable: false),
                    ConvertibleLoansTotal = table.Column<decimal>(nullable: false),
                    BankLoansTotal = table.Column<decimal>(nullable: false),
                    OtherLoansTotal = table.Column<decimal>(nullable: false),
                    HedgingLiabilitiesNonCurrent = table.Column<decimal>(nullable: false),
                    HedgingLiabilitiesCurrent = table.Column<decimal>(nullable: false),
                    InsuranceFundsNonCurrent = table.Column<decimal>(nullable: false),
                    InsuranceFundsCurrent = table.Column<decimal>(nullable: false),
                    DebtTotal = table.Column<decimal>(nullable: false),
                    AssetsHeldForSaleCurrent = table.Column<decimal>(nullable: false),
                    AssetsHeldForSaleNonCurrent = table.Column<decimal>(nullable: false),
                    BiologicalAssets = table.Column<decimal>(nullable: false),
                    CashRestrictedOrPledged = table.Column<decimal>(nullable: false),
                    ConvertibleLoansNonCurrent = table.Column<decimal>(nullable: false),
                    FinancialOrDerivativeInvestmentCurrentLiabilities = table.Column<decimal>(nullable: false),
                    LoanAndLoanReceivables = table.Column<decimal>(nullable: false),
                    OtherInvestments = table.Column<decimal>(nullable: false),
                    TradeAndOtherReceivablesNonCurrent = table.Column<decimal>(nullable: false),
                    DebtDueInYear1 = table.Column<decimal>(nullable: false),
                    DebtDueInYear2 = table.Column<decimal>(nullable: false),
                    DebtDueInYear5 = table.Column<decimal>(nullable: false),
                    DebtDueBeyond = table.Column<decimal>(nullable: false),
                    TotalDebtInMaturitySchedule = table.Column<decimal>(nullable: false),
                    FiscalYearChange = table.Column<decimal>(nullable: false),
                    FixedAssetsRevaluationReserve = table.Column<decimal>(nullable: false),
                    CurrentOtherFinancialLiabilities = table.Column<decimal>(nullable: false),
                    NonCurrentOtherFinancialLiabilities = table.Column<decimal>(nullable: false),
                    OtherFinancialLiabilities = table.Column<decimal>(nullable: false),
                    TotalLiabilitiesAsReported = table.Column<decimal>(nullable: false),
                    TotalEquityAsReported = table.Column<decimal>(nullable: false),
                    UnallocatedSurplus = table.Column<decimal>(nullable: false),
                    NetDebt = table.Column<decimal>(nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_TBalanceSheet", x => x.Id);
                });

            migrationBuilder.CreateTable(
                name: "TStockExchangeSecurity",
                schema: "MStar",
                columns: table => new
                {
                    Id = table.Column<Guid>(nullable: false),
                    ExchangeId = table.Column<string>(nullable: true),
                    CompanyName = table.Column<string>(nullable: true),
                    Symbol = table.Column<string>(nullable: true),
                    CUSIP = table.Column<string>(nullable: true),
                    CIK = table.Column<string>(nullable: true),
                    ISIN = table.Column<string>(nullable: true),
                    SEDOL = table.Column<string>(nullable: true),
                    InvestmentTypeId = table.Column<string>(nullable: true),
                    StockStatus = table.Column<string>(nullable: true),
                    DelistingDate = table.Column<DateTime>(nullable: false),
                    DelistingReason = table.Column<string>(nullable: true),
                    ExchangeSubMarketGlobalId = table.Column<string>(nullable: true),
                    ParValue = table.Column<decimal>(nullable: false),
                    SuspendedFlag = table.Column<string>(nullable: true),
                    IngestionTaskId = table.Column<Guid>(nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_TStockExchangeSecurity", x => x.Id);
                });
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "ClientConfigurations");

            migrationBuilder.DropTable(
                name: "IngestionTasks");

            migrationBuilder.DropTable(
                name: "TBalanceSheet",
                schema: "MStar");

            migrationBuilder.DropTable(
                name: "TStockExchangeSecurity",
                schema: "MStar");
        }
    }
}
